dictionaries["hsk1"] = {
	"name" : "HSK1 vocabulary (150 words) (English)",
	"desc" : "Hànyǔ Shuǐpíng Kǎoshì (HSK) (汉语水平考试)",
	"link" : "http://www.wohok.com",
	"language" : "zh-simp",
	"words": [
["爱","ài","Verb: to love"],
["八","bā","Number: 8"],
["爸爸","bà ba","Noun: dad"],
["北京","Běi jīng","Noun: Beijing"],
["杯子","bēi zi","Noun: cup, glass"],
["本","běn","Noun: root, basis, foundation, origin, capital; Measure Word: for books, files, etc."],
["不","bù","Adverb: no, not"],
["不客气","bú kè qi","Saying: you are welcome"],
["菜","cài","Noun: dish, vegetable"],
["茶","chá","Noun: tea"],
["吃","chī","Verb: to eat"],
["出租车","chū zū chē","Noun: taxi"],
["大","dà","Adjective: big, great"],
["打电话","dǎ diàn huà","Verb: to make a phone call"],
["的","de","Particle: to form an attribute"],
["点","diǎn","Noun: point, dot; Verb: to nod, to click; Measure Word: a little, a bit"],
["电脑","diàn nǎo","Noun: computer"],
["电视","diàn shì","Noun: TV(-set)"],
["电影","diàn yǐng","Noun: movie, film"],
["东西","dōng xi","Noun: thing"],
["都","dōu","Adverb: all, both; Pronoun: all, both"],
["读","dú","Verb: to read aloud"],
["对不起","duì bu qǐ","Saying: sorry, I'm sorry"],
["多","duō","Adjective: much, many"],
["多少","duō shao","Adverb: how many, how much"],
["二","èr","Number: 2"],
["儿子","ér zi","Noun: son"],
["饭馆","fàn guǎn","Noun: restaurant"],
["飞机","fēi jī","Noun: airplane"],
["分钟","fēn zhōng","Noun: minute"],
["高兴","gāo xìng","Adjective: happy, glad, cheerful"],
["个","gè","Measure Word: for almost everything"],
["工作","gōng zuò","Noun: job; Verb: to work"],
["狗","gǒu","Noun: dog"],
["汉语","hàn yǔ","Noun: Chinese language"],
["好","hǎo","Adjective: good, nice"],
["和","hé","Preposition: with; Conjunction: and"],
["喝","hē","Verb: to drink"],
["很","hěn","Adverb: very, quite"],
["后面","hòu miàn","Place: rear, back, behind"],
["回","huí","Verb: to return, to answer, to reply; Measure Word: for events of action"],
["会","huì","Noun: meeting, conference; Auxiliary Verb: can, to be able to"],
["火车站","huǒ chē zhàn","Noun: train station"],
["几","jǐ","Adverb: how many; Pronoun: several"],
["家","jiā","Noun: family, home, houshold; Measure Word: for businesses, families"],
["叫","jiào","Verb: to be called, to call, to shout"],
["今天","jīn tiān","Time: today"],
["九","jiǔ","Number: 9"],
["开","kāi","Verb: to open, to start, to drive (car, etc.)"],
["看","kàn","Verb: to see, to watch, to look at"],
["看见","kàn jiàn","Verb: to see, to catch sight of"],
["块","kuài","Measure Word: for a piece"],
["来","lái","Verb: to come, to arrive; Particle: ever since"],
["老师","lǎo shī","Noun: teacher"],
["了","le","Particle: indicating past or change"],
["冷","lěng","Adjective: cold"],
["里","lǐ","Place: in, inside; Measure Word: for 0.5 km"],
["零","líng","Number: 0"],
["六","liù","Number: 6"],
["吗","ma","Particle: to form a question"],
["妈妈","mā ma","Noun: mother"],
["买","mǎi","Verb: to buy"],
["猫","māo","Noun: cat"],
["没","méi","Adverb: not"],
["没关系","méi guān xi","Saying: it doesn't matter"],
["米饭","mǐ fàn","Noun: (cooked) rice"],
["明天","míng tiān","Time: tomorrow"],
["名字","míng zi","Noun: name"],
["那","nà","Pronoun: that"],
["哪","nǎ","Pronoun: which"],
["呢","ne","Particle: to build a question based on already mentioned subjects"],
["能","néng","Auxiliary Verb: to be able to"],
["你","nǐ","Pronoun: you (singular)"],
["年","nián","Noun: year"],
["女儿","nǚ ér","Noun: daughter"],
["朋友","péng you","Noun: friend"],
["漂亮","piào liang","Adjective: pretty, beautiful"],
["苹果","píng guǒ","Noun: apple"],
["七","qī","Number: 7"],
["钱","qián","Noun: money"],
["前面","qián miàn","Place: ahead, in front"],
["请","qǐng","Verb: to ask, to invite; Saying: please"],
["去","qù","Verb: to go"],
["热","rè","Adjective: hot, warm"],
["人","rén","Noun: person, people"],
["认识","rèn shi","Noun: understanding, knowledge, awareness; Verb: to know, to recognize, to understand, to be familiar with"],
["日","rì","Noun: day, sun"],
["三","sān","Number: 3"],
["上","shàng","Verb: to go up, to attend, to climb; Place: on, upon, previous, upper"],
["商店","shāng diàn","Noun: shop, store"],
["上午","shàng wǔ","Noun: morning"],
["少","shǎo","Adjective: few, little"],
["谁","shéi","Pronoun: who"],
["什么","shén me","Pronoun: what"],
["十","shí","Number: 10"],
["是","shì","Verb: is, to be"],
["时候","shí hou","Noun: time, moment, period"],
["书","shū","Noun: book"],
["水","shuǐ","Noun: Water"],
["水果","shuǐ guǒ","Noun: fruit"],
["睡觉","shuì jiào","Verb: to sleep, to go to bed"],
["说话","shuō huà","Verb: to speak, to talk, to gossip"],
["四","sì","Number: 4"],
["岁","suì","Measure Word: 'years old'"],
["他","tā","Pronoun: he"],
["她","tā","Pronoun: she"],
["太","tài","Adverb: too, extremely"],
["天气","tiān qì","Noun: weather"],
["听","tīng","Verb: to listen, to hear, to obey; Measure Word: for canned beverages"],
["同学","tóng xué","Noun: classmate"],
["喂","wèi","Verb: to feed, to breed; Saying: hello"],
["我","wǒ","Pronoun: I"],
["我们","wǒ men","Pronoun: we"],
["五","wǔ","Number: 5"],
["喜欢","xǐ huan","Verb: to like"],
["下","xià","Verb: descend, fall; Measure Word: for times of action; Place: below, down, under"],
["下午","xià wǔ","Noun: afternoon"],
["下雨","xià yǔ","Verb: to rain"],
["先生","xiān sheng","Noun: Mister (Mr.), teacher"],
["现在","xiàn zài","Time: now"],
["想","xiǎng","Verb: to think, to miss; Auxiliary Verb: to want"],
["小","xiǎo","Adjective: small"],
["小姐","xiǎo jiě","Noun: Miss, young lady"],
["写","xiě","Verb: to write"],
["些","xiē","Measure Word: some, few, several"],
["谢谢","xiè xie","Saying: thanks!"],
["星期","xīng qī","Noun: week"],
["学生","xué sheng","Noun: student, pupil"],
["学习","xué xí","Verb: to study, to learn"],
["学校","xué xiào","Noun: school"],
["一","yī","Number: 1"],
["衣服","yī fu","Noun: clothes"],
["医生","yī shēng","Noun: doctor"],
["医院","yī yuàn","Noun: hospital"],
["椅子","yǐ zi","Noun: chair"],
["有","yǒu","Verb: to have, to exist, to be"],
["月","yuè","Noun: month, moon"],
["在","zài","Preposition: at, on, in; Particle: for action in progress"],
["再见","zài jiàn","Saying: goodbye, see you"],
["怎么","zěn me","Adverb: how"],
["怎么样","zěn me yàng","Adverb: how is/are; Saying: how about that?"],
["这","zhè","Pronoun: this"],
["中国","Zhōng guó","Noun: China"],
["中午","zhōng wǔ","Noun: noon, midday"],
["住","zhù","Verb: to live, to stay, to reside"],
["桌子","zhuō zi","Noun: table"],
["字","zì","Noun: word, character"],
["做","zuò","Verb: to do, to make"],
["坐","zuò","Verb: to sit, to take (bus, train, etc.)"],
["昨天","zuó tiān","Time: yesterday"]
]};
