dictionaries["hsk2"] = {
	"name" : "HSK2 vocabulary (150 words) (English)",
	"desc" : "Hànyǔ Shuǐpíng Kǎoshì (HSK) (汉语水平考试)",
	"link" : "http://www.wohok.com",
	"language" : "zh-simp",
	"words": [
["吧","ba","Particle: indicating suggestion"],
["白","bái","Adjective: white, blank; Adverb: free of charge, for nothing"],
["百","bǎi","Number: 100"],
["帮助","bāng zhù","Noun: assistance, help; Verb: to help, to assist"],
["报纸","bào zhǐ","Noun: newspaper"],
["比","bǐ","Preposition: than, used for comparison"],
["别","bié","Verb: to leave, to distinguish; Adjective: other, another; Adverb: don't"],
["长","cháng","Noun: length; Adjective: long"],
["唱歌","chàng gē","Verb: to sing"],
["出","chū","Verb: to go out, to exceed, to happen; Measure Word: for dramas, plays, operas"],
["船","chuán","Noun: boat, ship"],
["穿","chuān","Verb: to wear"],
["次","cì","Noun: order, sequence; Measure Word: 'time(s)'"],
["从","cóng","Preposition: from"],
["错","cuò","Noun: mistake, error; Adjective: wrong"],
["大家","dà jiā","Pronoun: everybody, all"],
["打篮球","dǎ lán qiú","Verb: play basketball"],
["但是","dàn shì","Conjunction: but, however"],
["到","dào","Verb: to arrive, to reach; Preposition: to, until, up to"],
["得","de","Particle: used to link verb with adjective"],
["等","děng","Verb: to wait"],
["弟弟","dì di","Noun: younger brother"],
["第一","dì yī","Number: first, number one"],
["懂","dǒng","Verb: to understand, to know"],
["对","duì","Adjective: right, correct"],
["房间","fáng jiān","Noun: room"],
["非常","fēi cháng","Adverb: very"],
["服务员","fú wù yuán","Noun: waiter, service personnel"],
["高","gāo","Adjective: high, tall"],
["告诉","gào su","Verb: to tell"],
["哥哥","gē ge","Noun: older brother"],
["给","gěi","Verb: to give"],
["公共汽车","gōng gòng qì chē","Noun: bus"],
["公斤","gōng jīn","Noun: kilogram; Measure Word: kg"],
["公司","gōng sī","Noun: company"],
["贵","guì","Adjective: expensive"],
["过","guo","Particle: indicating action in the past"],
["还","hái","Adverb: still"],
["孩子","hái zi","Noun: child"],
["号","hào","Noun: number, day of month"],
["好吃","hǎo chī","Adjective: tasty, delicious"],
["黑","hēi","Adjective: black, dark"],
["红","hóng","Noun: dividend; Adjective: red, popular, revlutionary"],
["欢迎","huān yíng","Saying: welcome!"],
["回答","huí dá","Noun: answer; Verb: to answer, to reply"],
["机场","jī chǎng","Noun: airport"],
["鸡蛋","jī dàn","Noun: (chicken) egg"],
["件","jiàn","Measure Word: for events, things, clothes, etc."],
["教室","jiào shì","Noun: classroom"],
["姐姐","jiě jie","Noun: older sister"],
["介绍","jiè shào","Verb: to introduce, to recommend"],
["进","jìn","Verb: to advance, to enter"],
["近","jìn","Adjective: near, close"],
["就","jiù","Adverb: only, already; Preposition: with regard to; Conjunction: as soon as, right away, even if"],
["觉得","jué de","Verb: to think, to feel"],
["咖啡","kā fēi","Noun: coffee"],
["开始","kāi shǐ","Noun: beginning; Verb: to begin"],
["考试","kǎo shì","Noun: exam"],
["课","kè","Noun: class, lesson, course"],
["可能","kě néng","Adverb: might, maybe; Auxiliary Verb: can"],
["可以","kě yǐ","Auxiliary Verb: can, may, able to"],
["快","kuài","Adjective: quick, rapid; Adverb: soon, almost"],
["快乐","kuài lè","Adjective: happy"],
["累","lèi","Adjective: tired"],
["离","lí","Verb: to leave, to be away from"],
["两","liǎng","Number: two, some; Measure Word: 50 gram"],
["路","lù","Noun: road, path"],
["旅游","lǚ yóu","Noun: trip, jorney; Verb: to travel"],
["卖","mài","Verb: to sell"],
["慢","màn","Adjective: slow"],
["忙","máng","Adjective: busy"],
["每","měi","Adverb: each, per; Pronoun: all, each, every"],
["妹妹","mèi mei","Noun: younger sister"],
["门","mén","Noun: door; Measure Word: for lessons"],
["男人","nán rén","Noun: man, men"],
["您","nín","Pronoun: you (singular, polite)"],
["牛奶","niú nǎi","Noun: cow milk"],
["女人","nǚ rén","Noun: woman"],
["旁边","páng biān","Place: beside, aside"],
["跑步","pǎo bù","Verb: to run"],
["便宜","pián yi","Adjective: cheap, inexpensive"],
["票","piào","Noun: ticket"],
["起床","qǐ chuáng","Verb: to get up (from bed)"],
["妻子","qī zi","Noun: wife"],
["千","qiān","Number: 1000"],
["晴","qíng","Adjective: clear, sunny"],
["去年","qù nián","Time: last year"],
["让","ràng","Verb: to permit, to let sb. do sth."],
["上班","shàng bān","Verb: to go to work, to start work"],
["身体","shēn tǐ","Noun: body, health"],
["生病","shēng bìng","Verb: to get sick"],
["生日","shēng rì","Noun: birthday"],
["时间","shí jiān","Noun: time, period"],
["事情","shì qing","Noun: thing, affair, matter"],
["手表","shǒu biǎo","Noun: wrist watch"],
["手机","shǒu jī","Noun: mobile phone"],
["送","sòng","Verb: to deliver, to escort, to give, to send"],
["所以","suǒ yǐ","Conjunction: therefore, as a result, so"],
["它","tā","Pronoun: it"],
["题","tí","Noun: topic, problem; Verb: to inscribe, to mention"],
["踢足球","tī zú qiú","Verb: to play football"],
["跳舞","tiào wǔ","Verb: to dance"],
["外","wài","Adjective: foreign, external; Place: outside"],
["完","wán","Verb: to finish"],
["玩","wán","Verb: to play, to have fun"],
["晚上","wǎn shang","Time: evening"],
["为什么","wèi shén me","Adverb: why"],
["问","wèn","Verb: to ask"],
["问题","wèn tí","Noun: problem, question"],
["洗","xǐ","Verb: to wash"],
["西瓜","xī guā","Noun: watermelon"],
["希望","xī wàng","Noun: hope; Verb: to hope, to wish"],
["向","xiàng","Noun: direction; Verb: to face, to turn towards; Adverb: formerly, all along; Preposition: towards"],
["笑","xiào","Noun: smile; Verb: to smile, to laugh"],
["小时","xiǎo shí","Noun: hour"],
["新","xīn","Adjective: new"],
["姓","xìng","Noun: surname"],
["休息","xiū xi","Noun: rest; Verb: to rest"],
["雪","xuě","Noun: snow"],
["眼睛","yǎn jing","Noun: eye"],
["颜色","yán sè","Noun: colour"],
["羊肉","yáng ròu","Noun: mutton"],
["药","yào","Noun: medicine, drug"],
["要","yào","Auxiliary Verb: to want to, going to"],
["也","yě","Adverb: also"],
["已经","yǐ jīng","Adverb: already"],
["一起","yì qǐ","Adverb: together"],
["意思","yì si","Noun: meaning, opinion, idea"],
["阴","yīn","Adjective: cloudy, overcast"],
["因为","yīn wèi","Conjunction: because"],
["右边","yòu bian","Place: right, right side"],
["游泳","yóu yǒng","Noun: swimming; Verb: to swim"],
["鱼","yú","Noun: fish"],
["元","yuán","Measure Word: for money (Yuan, RMB)"],
["远","yuǎn","Adjective: far, distant"],
["运动","yùn dòng","Noun: movement, sports; Verb: to move about"],
["再","zài","Adverb: again, once more"],
["早上","zǎo shang","Time: early morning"],
["张","zhāng","Verb: to open up, to spread; Measure Word: for pieces, flat objects"],
["丈夫","zhàng fu","Noun: husband"],
["找","zhǎo","Verb: to look for, to seek"],
["着","zhe","Particle: indicating action in progress"],
["真","zhēn","Adverb: real, true, genuine"],
["正在","zhèng zài","Adverb: in the process of, in course of"],
["知道","zhī dào","Verb: to know, to be aware of"],
["准备","zhǔn bèi","Verb: to prepare"],
["自行车","zì xíng chē","Noun: bicycle, bike"],
["走","zǒu","Verb: to walk"],
["最","zuì","Adverb: most"],
["左边","zuǒ bian","Place: left, left side"]
]};

