dictionaries["hsk3"] = {
	"name" : "HSK3 vocabulary (300 words) (English)",
	"desc" : "Hànyǔ Shuǐpíng Kǎoshì (HSK) (汉语水平考试)",
	"link" : "http://www.wohok.com",
	"language" : "zh-simp",
	"words": [
["啊","a","Particle: showing approval"],
["阿姨","ā yí","Noun: aunt"],
["矮","ǎi","Adjective: low, short"],
["爱好","ài hào","Noun: hobby, interest; Verb: to like"],
["安静","ān jìng","Adjective: quiet, peaceful"],
["把","bǎ","Noun: handle; Verb: to grasp, to hold; Particle: for ba-sentences; Measure Word: for a bunch or objects with handle"],
["半","bàn","Number: half"],
["搬","bān","Verb: to move, to shift"],
["班","bān","Noun: class, team, squad; Measure Word: for groups, rankings, etc."],
["办法","bàn fǎ","Noun: method, way, means"],
["办公室","bàn gōng shì","Noun: office, bureau"],
["帮忙","bāng máng","Verb: to help, to do a favour"],
["饱","bǎo","Adjective: full (from eating)"],
["包","bāo","Noun: bag, package; Verb: to cover, to wrap, to hold, to include"],
["被","bèi","Preposition: by (for passive sentence)"],
["北方","běi fāng","Place: north, northern part of a country"],
["比较","bǐ jiào","Adverb: quite, rather, fairly, comparatively"],
["比赛","bǐ sài","Noun: competition, match; Verb: to compete"],
["必须","bì xū","Auxiliary Verb: to have to, to must"],
["鼻子","bí zi","Noun: nose"],
["变化","biàn huà","Noun: change, variation; Verb: to change, to vary"],
["表示","biǎo shì","Verb: to express, to show, to indicate"],
["表演","biǎo yǎn","Noun: performance; Verb: to perform, to act"],
["别人","bié ren","Pronoun: others, other people"],
["宾馆","bīn guǎn","Noun: hotel"],
["冰箱","bīng xiāng","Noun: fridge, icebox"],
["才","cái","Noun: ability, talent; Adverb: just, only if"],
["菜单","cài dān","Noun: menu"],
["参加","cān jiā","Verb: to attend, to take part, to join"],
["草","cǎo","Noun: grass, straw"],
["层","céng","Noun: layer, floor; Measure Word: for layer, story, floor"],
["差","chà","Verb: to lack, short of; Adjective: poor"],
["超市","chāo shì","Noun: supermarket"],
["衬衫","chèn shān","Noun: shirt, blouse"],
["成绩","chéng jì","Noun: score, achievement, grades"],
["城市","chéng shì","Noun: city, town"],
["迟到","chí dào","Verb: to be late"],
["厨房","chú fáng","Noun: kitchen"],
["除了","chú le","Conjunction: except for, apart from, besides"],
["出现","chū xiàn","Verb: to appear, to arise"],
["春","chūn","Noun: spring"],
["词语","cí yǔ","Noun: word, expression"],
["聪明","cōng ming","Adjective: clever, intelligent, smart"],
["打扫","dǎ sǎo","Verb: to clean"],
["打算","dǎ suàn","Noun: plan, intention; Verb: to plan, to think of, to calculate"],
["带","dài","Noun: band, belt, area, region; Verb: to wear, to carry, to bring, to lead"],
["蛋糕","dàn gāo","Noun: cake"],
["担心","dān xīn","Verb: to worry; Adjective: worried, anxious"],
["当然","dāng rán","Adverb: certainly, of course"],
["地","de","Particle: used before a verb"],
["灯","dēng","Noun: lamp, light"],
["低","dī","Adjective: low"],
["地方","dì fang","Noun: region, place, location"],
["地铁","dì tiě","Noun: subway"],
["地图","dì tú","Noun: map"],
["电梯","diàn tī","Noun: elevator"],
["电子邮件","diàn zǐ yóu jiàn","Noun: email"],
["东","dōng","Place: east"],
["冬","dōng","Noun: winter"],
["动物","dòng wù","Noun: animal"],
["段","duàn","Measure Word: for paragraphs, segments, periods, stories"],
["短","duǎn","Adjective: short, brief"],
["锻炼","duàn liàn","Verb: to exercise, to engage in physical exercise"],
["多么","duō me","Adverb: how, what"],
["饿","è","Adjective: hungry"],
["耳朵","ěr duo","Noun: ear"],
["而且","ér qiě","Conjunction: moreover, in addition, furthermore"],
["发烧","fā shāo","Verb: to have fever"],
["发现","fā xiàn","Verb: to discover, to find"],
["放","fàng","Verb: to let go, to put, have a vacation"],
["方便","fāng biàn","Adjective: convenient"],
["放心","fàng xīn","Verb: to rest, to be at ease"],
["分","fēn","Noun: minute, point, 0.01 yuan; Verb: to divide, to distinguish"],
["附近","fù jìn","Noun: vicinity; Adverb: nearby; Preposition: next to"],
["复习","fù xí","Noun: revision; Verb: to revise"],
["敢","gǎn","Auxiliary Verb: to dare"],
["干净","gān jìng","Adjective: clean, tidy"],
["感冒","gǎn mào","Noun: common cold; Verb: to catch a cold"],
["刚才","gāng cái","Time: just a moment ago"],
["跟","gēn","Verb: to follow; Preposition: with; Conjunction: and"],
["根据","gēn jù","Noun: basis, foundation; Verb: to base on; Preposition: according to, based on"],
["更","gèng","Adverb: even more"],
["公园","gōng yuán","Noun: park"],
["故事","gù shi","Noun: story, tale"],
["刮风","guā fēng","Verb: to be windy"],
["关","guān","Noun: mountain pass, barrier; Verb: to close, to shut, to turn off"],
["关系","guān xì","Noun: relationship, relation; Verb: to affect, to have to do with"],
["关心","guān xīn","Noun: concern; Verb: to care for"],
["关于","guān yú","Preposition: concerning, with regards to, about"],
["国家","guó jiā","Noun: country, state, nation"],
["过去","guò qù","Verb: to go over, to pass by; Adverb: past, former"],
["果汁","guǒ zhī","Noun: fruit juice"],
["害怕","hài pà","Verb: to be afraid, to fear"],
["还是","hái shì","Adverb: still, nevertheless; Conjunction: or"],
["河","hé","Noun: river"],
["黑板","hēi bǎn","Noun: blackboard"],
["护照","hù zhào","Noun: passport"],
["画","huà","Noun: picture, painting; Verb: to draw, to paint"],
["花","huā","Noun: flower; Verb: to spend"],
["花园","huā yuán","Noun: garden"],
["坏","huài","Adjective: bad, broken, spoiled"],
["还","huán","Verb: to give back, to return"],
["换","huàn","Verb: to change, to exchange"],
["环境","huán jìng","Noun: environment, surroundings"],
["黄","huáng","Verb: to fall through; Adjective: yellow, pornographic"],
["会议","huì yì","Noun: meeting, conference"],
["或者","huò zhě","Conjunction: or, possibly"],
["极","jí","Noun: pole; Adverb: extremely, highly"],
["记得","jì de","Verb: to remember"],
["几乎","jī hū","Adverb: almost, nearly"],
["机会","jī huì","Noun: opportunity, chance"],
["季节","jì jié","Noun: season, period"],
["检查","jiǎn chá","Noun: inspection; Verb: to check, to inspect, to examine"],
["简单","jiǎn dān","Adjective: simple, uncomplicated"],
["健康","jiàn kāng","Noun: health; Adjective: healthy"],
["见面","jiàn miàn","Verb: to meet, to see sb."],
["讲","jiǎng","Noun: speech, lecture; Verb: to speak, to explain, to negotiate"],
["脚","jiǎo","Noun: foot"],
["角","jiǎo","Noun: angle, corner, horn; Measure Word: for 0.1 yuan"],
["教","jiāo","Verb: to teach, to instruct"],
["借","jiè","Verb: to lend, to borrow, to make use of (an opportunity)"],
["接","jiē","Verb: to receive, to meet, to connect, to catch"],
["街道","jiē dào","Noun: street"],
["结婚","jié hūn","Noun: marriage, wedding; Verb: to marry"],
["解决","jiě jué","Verb: to settle (dispute), to resolve, to solve"],
["节目","jié mù","Noun: program, item"],
["节日","jié rì","Noun: holiday, festival"],
["结束","jié shù","Noun: termination, end; Verb: to finish, to end, to conclude"],
["经常","jīng cháng","Adverb: often, frequently"],
["经过","jīng guò","Verb: to pass, to go through; Preposition: after, as a result of"],
["经理","jīng lǐ","Noun: manager, director"],
["旧","jiù","Adjective: old, used, worn"],
["久","jiǔ","Adjective: long (time)"],
["举行","jǔ xíng","Verb: to hold (meeting, etc.)"],
["句子","jù zi","Noun: sentence"],
["决定","jué dìng","Noun: decision; Verb: to decide"],
["刻","kè","Verb: to cut, to carve; Measure Word: for quarter of an hour"],
["渴","kě","Adjective: thirsty"],
["可爱","kě ài","Adjective: cute, lovely"],
["客人","kè rén","Noun: guest, customer, visitor"],
["空调","kōng tiáo","Noun: air conditioning"],
["口","kǒu","Noun: mouth; Measure Word: for things with mouths or a mouth full of"],
["哭","kū","Verb: to cry, to weep"],
["裤子","kù zi","Noun: trousers"],
["筷子","kuài zi","Noun: chopsticks"],
["蓝","lán","Adjective: blue"],
["老","lǎo","Adjective: old; Adverb: always"],
["离开","lí kāi","Verb: to depart, to leave"],
["历史","lì shǐ","Noun: history"],
["礼物","lǐ wù","Noun: gift, present"],
["脸","liǎn","Noun: face"],
["练习","liàn xí","Noun: exercise, practice; Verb: to practice"],
["辆","liàng","Measure Word: for vehicles"],
["了解","liǎo jiě","Verb: to understand"],
["邻居","lín jū","Noun: neighbor"],
["楼","lóu","Noun: storied building; Measure Word: for floor"],
["绿","lǜ","Adjective: green"],
["马","mǎ","Noun: horse"],
["马上","mǎ shàng","Adverb: immediately, at once"],
["满意","mǎn yì","Verb: to satisfy; Adjective: satisfied"],
["帽子","mào zi","Noun: hat, cap"],
["米","mǐ","Noun: rice; Measure Word: for meter"],
["面包","miàn bāo","Noun: bread"],
["面条","miàn tiáo","Noun: noodles"],
["明白","míng bai","Verb: to understand; Adjective: clear, obvious"],
["拿","ná","Verb: to hold, to seize"],
["奶奶","nǎi nai","Noun: grandmother (father's mother)"],
["南","nán","Place: south"],
["难","nán","Adjective: difficult"],
["难过","nán guò","Verb: to feel sorry, sad"],
["年级","nián jí","Noun: grade, year"],
["年轻","nián qīng","Adjective: young"],
["鸟","niǎo","Noun: bird"],
["努力","nǔ lì","Noun: great effort; Verb: to strive, to work/study hard; Adjective: hard, hardworking"],
["爬山","pá shān","Noun: hiking; Verb: to climb a mountain"],
["盘子","pán zi","Noun: tray, plate, dish"],
["胖","pàng","Adjective: fat, plump"],
["啤酒","pí jiǔ","Noun: beer"],
["葡萄","pú tao","Noun: grape"],
["普通话","pǔ tōng huà","Noun: Mandarin"],
["骑","qí","Verb: to ride (animal or bike)"],
["奇怪","qí guài","Adjective: strange"],
["其实","qí shí","Adverb: actually, in fact"],
["其他","qí tā","Pronoun: other, others"],
["铅笔","qiān bǐ","Noun: pencil"],
["清楚","qīng chu","Adjective: clear, distinct"],
["秋","qiū","Noun: autumn, fall"],
["裙子","qún zi","Noun: skirt"],
["然后","rán hòu","Conjunction: then, afterwards"],
["热情 ","rè qíng","Noun: enthusiasm, passion; Adjective: enthusiastic, passionate, cordial"],
["认为","rèn wéi","Verb: to think, to believe, to consider"],
["认真","rèn zhēn","Adjective: conscientious, earnest, serious"],
["容易","róng yì","Adjective: easy"],
["如果","rú guǒ","Conjunction: if"],
["伞","sǎn","Noun: umbrella"],
["上网","shàng wǎng","Verb: to be on the internet"],
["生气","shēng qì","Verb: to be/get angry; Adjective: angry, mad"],
["声音","shēng yīn","Noun: voice, sound"],
["使","shǐ","Noun: envoy, messenger; Verb: to make, to cause, to use, to employ"],
["世界","shì jiè","Noun: world"],
["瘦","shòu","Adjective: thin, slim"],
["树","shù","Noun: tree"],
["舒服","shū fu","Adjective: comfortable"],
["叔叔","shū shu","Noun: uncle"],
["数学","shù xué","Noun: mathematics"],
["刷牙","shuā yá","Verb: to brush teeth"],
["双","shuāng","Adjective: two, pair, both; Measure Word: for a pair (of shoes, etc.)"],
["水平","shuǐ píng","Noun: level, standard; Adjective: horizontal"],
["司机","sī jī","Noun: driver"],
["虽然","suī rán","Conjunction: although"],
["太阳","tài yáng","Noun: sun"],
["糖","táng","Noun: sugar, sweets, candy"],
["特别","tè bié","Adjective: special, particular"],
["疼","téng","Noun: pain; Verb: to ache, to hurt"],
["提高","tí gāo","Verb: to raise, to increase"],
["体育","tǐ yù","Noun: sports"],
["甜","tián","Adjective: sweet"],
["条","tiáo","Noun: strip, clause; Measure Word: for long thin things"],
["同事","tóng shì","Noun: colleague"],
["同意","tóng yì","Verb: to agree, to consent, to approve"],
["头发","tóu fa","Noun: hair (on the head)"],
["突然","tū rán","Adjective: sudden, abrupt; Adverb: suddenly, unexpectedly"],
["图书馆","tú shū guǎn","Noun: library"],
["腿","tuǐ","Noun: leg"],
["万","wàn","Number: 10000"],
["碗","wǎn","Noun: bowl"],
["完成","wán chéng","Verb: to complete, to accomplish"],
["忘记","wàng jì","Verb: to forget"],
["为","wèi","Verb: to do, to act, to be, to become; Preposition: for (sb.)"],
["位","wèi","Noun: position, place, seat; Measure Word: for people"],
["为了","wèi le","Preposition: for, in order to"],
["文化","wén huà","Noun: culture"],
["西","xī","Place: west"],
["习惯","xí guàn","Noun: habit, usual practice, custom; Verb: to be/get used to"],
["洗手间","xǐ shǒu jiān","Noun: toilet"],
["洗澡","xǐ zǎo","Verb: to take a shower, to have a bath"],
["夏","xià","Noun: summer"],
["先","xiān","Adverb: early, former, first, before"],
["像","xiàng","Noun: picture, portrait; Verb: be/look like, to appear, to seem"],
["香蕉","xiāng jiāo","Noun: banana"],
["相同","xiāng tóng","Adjective: identical, same"],
["相信","xiāng xìn","Verb: to believe in, have faith in"],
["小心","xiǎo xīn","Verb: to be careful; Adjective: careful; Saying: Take care!"],
["校长","xiào zhǎng","Noun: headmaster, president (university)"],
["鞋","xié","Noun: shoe"],
["信","xìn","Noun: letter, trust; Verb: to believe, to trust"],
["新闻","xīn wén","Noun: news"],
["新鲜","xīn xiān","Adjective: fresh (food, experience, etc.)"],
["行李箱","xíng li xiāng","Noun: suitcase"],
["兴趣","xìng qù","Noun: interest"],
["熊猫","xióng māo","Noun: panda"],
["需要","xū yào","Noun: needs; Verb: to need, to want"],
["选择","xuǎn zé","Noun: choice, option; Verb: to choose, to select"],
["眼镜","yǎn jìng","Noun: eyeglasses"],
["要求","yāo qiú","Noun: demand, requirement; Verb: to require, to demand"],
["爷爷","yé ye","Noun: grandfather (father's father)"],
["一般","yì bān","Adjective: ordinary, general, common; Adverb: in general, generally"],
["一边","yì biān","Place: one side; Adverb: on the one hand"],
["一定","yí dìng","Adjective: definite, fixed, given; Adverb: surely, certainly"],
["一共","yí gòng","Adverb: althogether"],
["以后","yǐ hòu","Time: after, afterwards"],
["一会儿","yí huì r","Time: a while; Adverb: in a moment, a little while"],
["以前","yǐ qián","Time: before; Adverb: previous, formerly"],
["以为","yǐ wéi","Verb: to think (wrongly), to be under the (wrong) impression"],
["一样","yí yàng","Adverb: alike, equal to"],
["一直","yī zhí","Adverb: always, continuously, straight"],
["银行","yín háng","Noun: bank (for money)"],
["音乐","yīn yuè","Noun: music"],
["应该","yīng gāi","Auxiliary Verb: should, ought to"],
["影响","yǐng xiǎng","Noun: influence, effect; Verb: to influence, to affect"],
["用","yòng","Verb: to use, to employ, to apply"],
["又","yòu","Adverb: again"],
["有名","yǒu míng","Adjective: famous, well known"],
["游戏","yóu xì","Noun: game, play"],
["遇到","yù dào","Verb: to meet, to run into"],
["愿意","yuàn yì","Auxiliary Verb: to be willing, be ready, to wish, to want"],
["越","yuè","Verb: to exceed, to climb over, to surpass"],
["月亮","yuè liang","Noun: moon"],
["云","yún","Noun: cloud"],
["站","zhàn","Noun: station, stop; Verb: to stand, to stop, to halt"],
["长","zhǎng","Noun: chief, head; Verb: to grow, to develop"],
["照顾","zhào gù","Verb: to take care of, to look after"],
["着急","zháo jí","Verb: to worry"],
["照片","zhào piàn","Noun: photo, picture"],
["照相机","zhào xiàng jī","Noun: camera"],
["只","zhǐ","Adverb: only, just, merely"],
["种","zhǒng","Noun: species, race, breed; Measure Word: type, kind, sort or for languages"],
["中间","zhōng jiān","Place: between, in the middle, mid"],
["重要","zhòng yào","Adjective: important"],
["终于","zhōng yú","Adverb: at last, finally, eventually"],
["周末","zhōu mò","Noun: weekend"],
["祝","zhù","Verb: to wish, to express good wishes"],
["主要","zhǔ yào","Adjective: main, principal, major"],
["注意","zhù yì","Verb: to pay attention to"],
["字典","zì diǎn","Noun: dictionary, character book"],
["自己","zì jǐ","Pronoun: oneself, self"],
["总是","zǒng shì","Adverb: always"],
["最近","zuì jìn","Adverb: recently, lately, soon"],
["作业","zuò yè","Noun: homework, task, work"],
["作用","zuò yòng","Noun: action, function, impact, effect; Verb: to affect "]
]};

