dictionaries["hsk4"] = {
	"name" : "HSK4 vocabulary (600 words) (English)",
	"desc" : "Hànyǔ Shuǐpíng Kǎoshì (HSK) (汉语水平考试)",
	"link" : "http://www.wohok.com",
	"language" : "zh-simp",
	"words": [
["爱情","ài qíng","Noun: love"],
["暗","àn","Adjective: dark"],
["安排","ān pái","Noun: plan; Verb: to plan, to arrange"],
["安全","ān quán","Noun: safety; Adjective: safe, secure"],
["按时","àn shí","Adjective: on time, on schedule"],
["按照","àn zhào","Preposition: according to"],
["抱","bào","Verb: to hug, to embrace, to hold"],
["报道","bào dào","Noun: report; Verb: to report"],
["保护","bǎo hù","Noun: protection; Verb: to protect, to safeguard"],
["包括","bāo kuò","Verb: to include, to consist of"],
["报名","bào míng","Verb: to sign up, to register"],
["抱歉","bào qiàn","Saying: sorry! my apologies!"],
["保证","bǎo zhèng","Noun: guarantee; Verb: to guarantee, to ensure, to assure"],
["倍","bèi","Measure Word: for times, -fold"],
["笨","bèn","Adjective: stupid, foolish"],
["本来","běn lái","Adjective: original; Adverb: originally, at first"],
["笔记本","bǐ jì běn","Noun: notebook"],
["毕业","bì yè","Verb: to graduate, to finish school"],
["遍","biàn","Adverb: all over; Measure Word: for a time"],
["表达","biǎo dá","Verb: to express, to convey"],
["表格","biǎo gé","Noun: form, table"],
["表扬","biǎo yáng","Verb: to praise, to commend"],
["标准","biāo zhǔn","Noun: standard, norm; Adjective: standard"],
["饼干","bǐng gān","Noun: buscuit, cookie"],
["并且","bìng qiě","Conjunction: and, besides, moreover"],
["博士","bó shì","Noun: doctor, Ph.D."],
["不但","bú dàn","Conjunction: not only"],
["不得不","bù dé bù","Auxiliary Verb: to have to, cannot but"],
["部分","bù fen","Noun: part, section"],
["不管","bù guǎn","Conjunction: regardless of, no matter what/how"],
["不过","bú guò","Adverb: only, just, no more than; Conjunction: but, however"],
["不仅","bù jǐn","Conjunction: not only, not just"],
["擦","cā","Verb: to wipe, to rub, to erase"],
["猜","cāi","Verb: to guess"],
["材料","cái liào","Noun: material, data, stuff"],
["参观","cān guān","Verb: to visit, to look around"],
["差不多","chà bu duō","Adjective: almost, more or less"],
["尝","cháng","Verb: to taste; Adverb: once"],
["场","chǎng","Noun: field, place; Measure Word: for events, happenings, etc."],
["长城","Cháng chéng","Noun: the Great Wall"],
["长江","Cháng jiāng","Noun: Yangtze river"],
["吵","chǎo","Verb: to quarrel; Adjective: noisy"],
["超过","chāo guò","Verb: to surpass, to exceed"],
["成功","chéng gōng","Noun: success; Verb: to succeed"],
["诚实","chéng shí","Adjective: honest, truthful"],
["成熟","chéng shú","Adjective: mature"],
["成为","chéng wéi","Verb: to become, to turn into"],
["乘坐","chéng zuò","Verb: to ride (in a vehicle)"],
["吃惊","chī jīng","Verb: to be startled, to be shocked, to be amazed"],
["重新","chóng xīn","Adverb: again"],
["抽烟","chōu yān","Verb: to smoke (a cigarette, etc.)"],
["出差","chū chāi","Verb: to go on a business trip"],
["出发","chū fā","Verb: to leave, to set out"],
["出生","chū shēng","Verb: to be born"],
["传真","chuán zhēn","Noun: fax"],
["窗户","chuāng hu","Noun: window"],
["词典","cí diǎn","Noun: dictionary"],
["从来","cóng lái","Adverb: always, ever since, at all times"],
["粗心","cū xīn","Adjective: careless, thoughtless"],
["答案","dá àn","Noun: answer, solution"],
["打扮","dǎ ban","Noun: style of dressing; Verb: to decorate, to dress up"],
["大概","dà gài","Adverb: probably, roughly"],
["打扰","dǎ rǎo","Verb: to disturb"],
["大使馆","dà shǐ guǎn","Noun: embassy"],
["打印","dǎ yìn","Verb: to print, to seal, to stamp"],
["大约","dà yuē","Adverb: approximately"],
["打折","dǎ zhé","Verb: to give discount"],
["打针","dǎ zhēn","Verb: to inject"],
["戴","dài","Verb: to put on, to wear, to respect, to support"],
["代表","dài biǎo","Noun: representative; Verb: to represent"],
["大夫","dài fu","Noun: doctor"],
["代替","dài tì","Noun: replacement; Verb: to replace, to substitute; Preposition: instead of"],
["当","dāng","Verb: to act as, to administer; Auxiliary Verb: should, ought; Adjective: equal; Conjunction: when, during"],
["当地","dāng dì","Noun: locality; Adjective: local"],
["当时","dāng shí","Time: at that time, then"],
["刀","dāo","Noun: knife"],
["到处","dào chù","Adverb: everywhere, at all places"],
["到底","dào dǐ","Adverb: finally, in the end"],
["道歉","dào qiàn","Verb: to apologize"],
["导游","dǎo yóu","Noun: tour guide"],
["得意","dé yì","Adjective: pleased with oneself"],
["得","děi","Auxiliary Verb: to have to"],
["等","děng","Particle: etc., and so on"],
["底","dǐ","Noun: background, end, bottom, base"],
["地球","dì qiú","Noun: earth (planet)"],
["地址","dì zhǐ","Noun: address"],
["掉","diào","Verb: to fall, to drop, to lose, to turn"],
["调查","diào chá","Noun: investigation, survey; Verb: to investigate, to survey"],
["丢","diū","Verb: to lose, to throw"],
["动作","dòng zuò","Noun: movement"],
["堵车","dǔ chē","Noun: traffic jam"],
["肚子","dù zi","Noun: belly, abdomen"],
["断","duàn","Verb: to cut off, to break, to judge, to decide; Adverb: absolutely, definitely"],
["对","duì","Preposition: for, to, towards"],
["对话","duì huà","Noun: dialog"],
["对面","duì miàn","Place: opposite"],
["顿","dùn","Noun: pause; Verb: to stop, to pause, to arrange; Measure Word: for meals, beatings, etc."],
["朵","duǒ","Measure Word: for flowers, clouds, etc."],
["而","ér","Conjunction: and, but, yet"],
["儿童","ér tóng","Noun: child"],
["发","fā","Verb: to send out, to issue, to develop; Measure Word: for gunshots"],
["法律","fǎ lǜ","Noun: law"],
["发生","fā shēng","Verb: to happen, to occur, to take place"],
["发展","fā zhǎn","Noun: development, growth; Verb: to develop, to grow"],
["反对","fǎn duì","Verb: to fight against, to oppose"],
["烦恼","fán nǎo","Noun: worries; Adjective: worried, troubled"],
["范围","fàn wéi","Noun: scope limit, range"],
["翻译","fān yì","Noun: translation, translator; Verb: to translate"],
["反映","fǎn yìng","Noun: reflection; Verb: to reflect, to mirror"],
["方法","fāng fǎ","Noun: method, way"],
["方面","fāng miàn","Noun: aspect, respect"],
["放弃","fàng qì","Verb: to give up"],
["放暑假","fàng shǔ jià","Verb: to take summer vacation"],
["访问","fǎng wèn","Noun: visit; Verb: to visit, to interview"],
["方向","fāng xiàng","Noun: direction, orientation"],
["份","fèn","Noun: part, share, portion, copy; Measure Word: for newspaper, papers, reports, contracts"],
["分之","fēn zhī","Saying: used for fractions and percentages"],
["丰富","fēng fù","Adjective: rich, plentiful"],
["风景","fēng jǐng","Noun: scenery, landscape"],
["否则","fǒu zé","Conjunction: otherwise"],
["富","fù","Adjective: rich"],
["符合","fú hé","Verb: to accord with, to conform to"],
["父亲","fù qīn","Noun: father"],
["复印","fù yìn","Verb: to (photo)copy"],
["复杂","fù zá","Adjective: complicated, complex"],
["负责","fù zé","Verb: to be responsible for"],
["改变","gǎi biàn","Verb: to change"],
["干","gàn","Verb: to do, to work"],
["干杯","gān bēi","Saying: Cheers!"],
["感动","gǎn dòng","Verb: to move sb., to touch (emotionally)"],
["感觉","gǎn jué","Noun: feeling, sense; Verb: to feel"],
["感情","gǎn qíng","Noun: emotion, feeling"],
["感谢","gǎn xiè","Noun: gratitude; Verb: to thank, to be grateful"],
["干燥","gān zào","Adjective: dry"],
["刚刚","gāng gāng","Adverb: just now, a moment ago"],
["高级","gāo jí","Adjective: high level, high grade, advanced"],
["各","gè","Pronoun: each, every"],
["个子","gè zi","Noun: height, stature"],
["工具","gōng jù","Noun: tool, utensil"],
["公里","gōng lǐ","Noun: kilometer; Measure Word: for km"],
["共同","gòng tóng","Adjective: common, joint, together"],
["工资","gōng zī","Noun: salary, wages"],
["够","gòu","Verb: to reach, to be enough; Adjective: be enough; Adverb: enough"],
["购物","gòu wù","Verb: to go shopping"],
["孤单","gū dān","Adjective: lone, lonely"],
["估计","gū jì","Verb: to estimate"],
["顾客","gù kè","Noun: client, customer"],
["鼓励","gǔ lì","Verb: to encourage, to urge"],
["故意","gù yì","Adverb: on purpose, deliberately"],
["鼓掌","gǔ zhǎng","Verb: to applaud"],
["挂","guà","Verb: to hang (up)"],
["关键","guān jiàn","Noun: key, crucial point"],
["管理","guǎn lǐ","Noun: management; Verb: to manage"],
["观众","guān zhòng","Noun: audience, spectators"],
["逛","guàng","Verb: to stroll"],
["光","guāng","Noun: light, ray; Adjective: naked; Adverb: only, merely"],
["广播","guǎng bō","Noun: broadcasting; Verb: to broadcast"],
["广告","guǎng gào","Noun: advertisement; Verb: to advertise"],
["规定","guī dìng","Noun: regulations, provision; Verb: to fix, to stipulate"],
["过","guò","Verb: to pass, to cross, to spend time"],
["过程","guò chéng","Noun: process, course"],
["国际","guó jì","Adjective: international"],
["果然","guǒ rán","Adverb: as expected"],
["害羞","hài xiū","Adjective: shy"],
["海洋","hǎi yáng","Noun: ocean"],
["汗","hàn","Noun: sweat"],
["寒假","hán jià","Noun: winter vacation"],
["航班","háng bān","Noun: scheduled flight, flight number"],
["好处","hǎo chu","Noun: benefit, advantage"],
["号码","hào mǎ","Noun: number"],
["好像","hǎo xiàng","Verb: to seem, to be like, look like"],
["合格","hé gé","Adjective: qualified"],
["合适","hé shì","Adjective: suitable, appropriate"],
["盒子","hé zi","Noun: box, case"],
["厚","hòu","Adjective: thick, deep"],
["后悔","hòu huǐ","Verb: to regret, to repent"],
["后来","hòu lái","Adverb: afterwards, later"],
["猴子","hóu zi","Noun: monkey"],
["忽然","hū rán","Adverb: suddenly"],
["护士","hù shi","Noun: nurse"],
["互相","hù xiāng","Adverb: each other"],
["怀疑","huái yí","Noun: doubt, suspicion; Verb: to doubt, to suspect"],
["回忆","huí yì","Noun: recollection; Verb: to recall, to recollect"],
["火","huǒ","Noun: fire"],
["获得","huò dé","Verb: to obtain, to acquire"],
["活动","huó dòng","Noun: activity; Verb: to move about; Adjective: active"],
["活泼","huó pō","Adjective: lively, vivid"],
["寄","jì","Verb: to send, to mail"],
["基础","jī chǔ","Noun: base, foundation, basis"],
["激动","jī dòng","Verb: to excite; Adjective: exciting"],
["集合","jí hé","Noun: congregation; Verb: to gather, to assemble"],
["计划","jì huà","Noun: plan, project, program; Verb: to plan"],
["积极","jī jí","Adjective: positive, active"],
["积累","jī lěi","Noun: accumulation; Verb: to accumulate"],
["极其","jí qí","Adverb: extremely"],
["既然","jì rán","Conjunction: this being the case"],
["及时","jí shí","Adjective: in time; Adverb: without delay"],
["即使","jí shǐ","Conjunction: even if, even thoug"],
["技术","jì shù","Noun: technology, skill, technique"],
["继续","jì xù","Noun: continuation; Verb: to continue, to go on"],
["记者","jì zhě","Noun: reporter, journalist"],
["假","jiǎ","Adjective: fake, false"],
["加班","jiā bān","Verb: to work overtime"],
["价格","jià gé","Noun: price"],
["家具","jiā jù","Noun: furniture"],
["加油站","jiā yóu zhàn","Noun: gas station"],
["坚持","jiān chí","Verb: to stick to, to persist in, to insist on"],
["减肥","jiǎn féi","Verb: to lose weight"],
["减少","jiǎn shǎo","Verb: to reduce, to decrease"],
["降低","jiàng dī","Verb: to reduce, to lower"],
["奖金","jiǎng jīn","Noun: premium, award money, bonus"],
["将来","jiāng lái","Noun: future; Adverb: in the future"],
["交","jiāo","Verb: to hand over, to intersect, to associate with"],
["骄傲","jiāo ào","Verb: to be proud of sth.; Adjective: arrogant, conceited"],
["交流","jiāo liú","Noun: communication, exchange; Verb: to exchange, to communicate"],
["教授","jiào shòu","Noun: professor; Verb: to instruct, to lecture on"],
["交通","jiāo tōng","Noun: traffic"],
["教育","jiào yù","Noun: educatione; Verb: to teach"],
["饺子","jiǎo zi","Noun: dumpling"],
["结果","jié guǒ","Noun: result, outcome; Conjunction: finally, at last"],
["解释","jiě shì","Noun: explanation; Verb: to explain"],
["接受","jiē shòu","Verb: to accept, to receive"],
["节约","jié yuē","Verb: to economize, to conserve"],
["尽管","jǐn guǎn","Adverb: unhesitatingly; Conjunction: in spite of, although, despite"],
["进行","jìn xíng","Verb: to be in progress, be underway"],
["紧张","jǐn zhāng","Adjective: nervous, tense, in short supply"],
["禁止","jìn zhǐ","Verb: to prohibit, to forbid, to ban"],
["精彩","jīng cǎi","Adjective: brilliant, excellent, splendid"],
["警察","jǐng chá","Noun: police"],
["经济","jīng jì","Noun: economy"],
["京剧","jīng jù","Noun: Beijing Opera"],
["经历","jīng lì","Noun: experience; Verb: to experience"],
["竟然","jìng rán","Adverb: unexpectedly"],
["精神","jīng shén","Noun: spirit, mind"],
["经验","jīng yàn","Noun: experience; Verb: to experience"],
["竞争","jìng zhēng","Noun: competition; Verb: to compete"],
["镜子","jìng zi","Noun: mirror"],
["究竟","jiū jìng","Adverb: after all, actually"],
["举办","jǔ bàn","Verb: to hold, to conduct"],
["拒绝","jù jué","Verb: to refuse, to decline"],
["距离","jù lí","Noun: distance; Verb: to be apart from"],
["开玩笑","kāi wán xiào","Verb: to play a joke, to make fun of"],
["看法","kàn fǎ","Noun: view, opinion"],
["考虑","kǎo lǜ","Noun: consideration; Verb: to think over, to consider"],
["棵","kē","Measure Word: for trees, plants, etc."],
["可怜","kě lián","Adjective: pitiful, poor, pathetic"],
["可是","kě shì","Conjunction: but"],
["咳嗽","ké sou","Noun: cough; Verb: to cough"],
["可惜","kě xī","Adjective: it is a pity, what a pity"],
["科学","kē xué","Noun: science; Adjective: scientific"],
["肯定","kěn dìng","Verb: to affirm, to confirm; Adjective: certain, definite; Adverb: certainly, definitely"],
["恐怕","kǒng pà","Adverb: I'm afraid that"],
["空气","kōng qì","Noun: air, atmosphere"],
["苦","kǔ","Adjective: bitter, miserable"],
["宽","kuān","Adjective: wide, broad"],
["困","kùn","Adjective: sleepy, tired"],
["困难","kùn nan","Noun: difficulty, problem; Adjective: difficult"],
["扩大","kuò dà","Verb: to expand, to enlarge"],
["辣","là","Adjective: spicy"],
["拉","lā","Verb: to pull"],
["垃圾桶","lā jī tǒng","Noun: rubbish bin"],
["来不及","lái bu jí","Verb: there's not enough time"],
["来得及","lái de jí","Verb: there is still time to do sth."],
["懒","lǎn","Adjective: lazy"],
["浪费","làng fèi","Verb: to waste"],
["浪漫","làng màn","Adjective: romantic"],
["老虎","lǎo hǔ","Noun: tiger"],
["冷静","lěng jìng","Adjective: calm, cool-headed, quite"],
["理发","lǐ fà","Verb: to have a haircut"],
["厉害","lì hai","Adjective: awesome, terrible, strict, severe, difficult to deal with"],
["理解","lǐ jiě","Noun: comprehension, understanding; Verb: to comprehend, to understand"],
["礼貌","lǐ mào","Noun: politeness, courtesy"],
["力气","lì qi","Noun: strength"],
["例如","lì rú","Adverb: for example"],
["理想","lǐ xiǎng","Noun: ideal, dream"],
["俩","liǎ","Number: two (people)"],
["连","lián","Verb: to link, to join, to connect; Adverb: even"],
["联系","lián xì","Noun: contact, connection; Verb: to contact"],
["亮","liàng","Verb: to shine, to show, to reveal; Adjective: bright, clear, shiny"],
["凉快","liáng kuai","Adjective: pleasantly cool"],
["聊天","liáo tiān","Verb: to chat"],
["另外","lìng wài","Conjunction: in addition, morover, furthermore"],
["留","liú","Verb: to keep, to remain, to stay, to leave (a message, etc.)"],
["流泪","liú lèi","Verb: to shed tears"],
["流利","liú lì","Adjective: fluent"],
["流行","liú xíng","Verb: to spread; Adjective: popular, fashionable"],
["留学","liú xué","Verb: to study abroad"],
["律师","lǜ shī","Noun: lawyer"],
["乱","luàn","Noun: disorder; Verb: to cause disorder; Adjective: in a mess, confused"],
["麻烦","má fan","Verb: to trouble sb.; Adjective: troublesome"],
["马虎","mǎ hu","Adjective: careless, negligent, casual"],
["满","mǎn","Verb: to fill, to satisfy; Adjective: full, satisfied"],
["毛巾","máo jīn","Noun: towel"],
["美丽","měi lì","Adjective: beautiful"],
["梦","mèng","Noun: dream"],
["密码","mì mǎ","Noun: password"],
["免费","miǎn fèi","Adjective: free (of charge)"],
["民族","mín zú","Noun: nationality, ethnic group"],
["目的","mù dì","Noun: purpose, aim"],
["母亲","mǔ qīn","Noun: mother"],
["耐心","nài xīn","Noun: patience; Adjective: patient"],
["难道","nán dào","Adverb: don't tell me ..., is it possible that ..."],
["难受","nán shòu","Verb: to be difficult to bear"],
["内","nèi","Place: inside, inner"],
["内容","nèi róng","Noun: content, substance"],
["能力","néng lì","Noun: ability, capability"],
["年龄","nián líng","Noun: age (of a person)"],
["弄","nòng","Verb: to do, to make"],
["农村","nóng cūn","Noun: village, rural area"],
["暖和","nuǎn huo","Adjective: warm"],
["偶尔","ǒu ěr","Adverb: occasionally"],
["排列","pái liè","Noun: arrangement, permutation; Verb: to arrange, to put in order"],
["判断","pàn duàn","Noun: decision, judgement; Verb: to decide, to judge"],
["陪","péi","Verb: to accompany"],
["皮肤","pí fū","Noun: skin"],
["批评","pī píng","Noun: criticism; Verb: to criticize"],
["脾气","pí qi","Noun: temperament, temper"],
["骗","piàn","Verb: to cheat, to swindle"],
["篇","piān","Measure Word: for chapters, articles, etc."],
["乒乓球","pīng pāng qiú","Noun: table tennis"],
["平时","píng shí","Noun: in peacetime; Adverb: normally"],
["瓶子","píng zi","Noun: bottle"],
["破","pò","Verb: to break, to destroy; Adjective: broken, damaged"],
["普遍","pǔ biàn","Adjective: universal, general"],
["其次","qí cì","Adverb: next, secondary; Conjunction: secondly"],
["起飞","qǐ fēi","Verb: to take off"],
["气候","qì hòu","Noun: climate, atmosphere"],
["起来","qǐ lái","Verb: to stand up, to get up"],
["其中","qí zhōng","Adverb: among, in"],
["千万","qiān wàn","Number: 10 million; Adjective: countless, many; Adverb: must, be sure to"],
["签证","qiān zhèng","Noun: visa"],
["墙","qiáng","Noun: wall"],
["桥","qiáo","Noun: bridge"],
["敲","qiāo","Verb: to knock"],
["巧克力","qiǎo kè lì","Noun: chocolate"],
["亲戚","qīn qi","Noun: relatives"],
["轻","qīng","Adjective: light, small in number, unimportant"],
["请假","qǐng jià","Verb: to ask for leave"],
["请客","qǐng kè","Verb: to invite sb. for dinner"],
["情况","qíng kuàng","Noun: circumstance, situation"],
["轻松","qīng sōng","Adjective: relaxed, easy"],
["穷","qióng","Adjective: poor"],
["取","qǔ","Verb: to take, to get"],
["区别","qū bié","Noun: difference; Verb: to distinguish"],
["全部","quán bù","Adjective: whole, entire, complete"],
["却","què","Conjunction: but, yet"],
["缺点","quē diǎn","Noun: weakness, shortcoming"],
["缺少","quē shǎo","Noun: lack, shortage; Verb: to lack, to be short of"],
["确实","què shí","Adjective: indeed, really; Adverb: for sure, indeed"],
["群","qún","Measure Word: for group, crowd, etc."],
["然而","rán ér","Conjunction: however, but"],
["热闹","rè nao","Adjective: lively, busy"],
["任何","rèn hé","Adjective: any, whichever, whatever"],
["人民币","rén mín bì","Noun: RMB, Chinese Yuan"],
["任务","rèn wu","Noun: mission, task"],
["扔","rēng","Verb: to throw (away)"],
["仍然","réng rán","Adverb: still, yet"],
["日记","rì jì","Noun: diary"],
["入口","rù kǒu","Noun: entrance"],
["软","ruǎn","Adjective: soft"],
["散步","sàn bù","Verb: to take/to go for a walk"],
["森林","sēn lín","Noun: forest"],
["沙发","shā fā","Noun: sofa"],
["商量","shāng liang","Verb: to consult, to discuss"],
["伤心","shāng xīn","Adjective: sad, grievous, brokenhearted"],
["稍微","shāo wēi","Adverb: a little bit"],
["社会","shè huì","Noun: society"],
["深","shēn","Adjective: deep, dark (color, etc.)"],
["申请","shēn qǐng","Noun: application; Verb: to apply for"],
["甚至","shèn zhì","Adverb: even"],
["剩","shèng","Verb: to remain"],
["省","shěng","Noun: province; Verb: to save, to omit"],
["生活","shēng huó","Noun: lif; Verb: to live"],
["生命","shēng mìng","Noun: life"],
["试","shì","Noun: experiment, examination, test; Verb: to test, to attempt"],
["失败","shī bài","Noun: defeat, failure; Verb: to lose, to be defeated"],
["市场","shì chǎng","Noun: market"],
["十分","shí fēn","Adverb: very, completely, fully, utterly, absolutely"],
["师傅","shī fu","Noun: master, teacher, used to respectfully address older men"],
["适合","shì hé","Verb: to fit, to suit"],
["实际","shí jì","Noun: reality, practice; Adjective: realistic, practical"],
["世纪","shì jì","Noun: century"],
["食品","shí pǐn","Noun: food"],
["湿润","shī rùn","Adjective: moist, humid"],
["失望","shī wàng","Noun: disappointment; Verb: to lose hope; Adjective: disappointed"],
["适应","shì yìng","Verb: to fit, to suit, to adabt"],
["使用","shǐ yòng","Verb: to use"],
["实在","shí zài","Adjective: real, true; Adverb: really, in fact"],
["狮子","shī zi","Noun: lion"],
["收","shōu","Verb: to accept, to receive"],
["受不了","shòu bù liǎo","Adjective: unbearable"],
["受到","shòu dào","Verb: to receive, to suffer"],
["首都","shǒu dū","Noun: capital city"],
["售货员","shòu huò yuán","Noun: salesperson"],
["收入","shōu rù","Noun: income, revenue; Verb: to take in"],
["收拾","shōu shi","Verb: to put in order, to tidy up, to punish"],
["首先","shǒu xiān","Adverb: first of all"],
["输","shū","Verb: to transport, to lose, to be beaten"],
["数量","shù liàng","Noun: amount, quantity"],
["熟悉","shú xī","Verb: to be familiar with"],
["数字","shù zì","Noun: figure, number"],
["帅","shuài","Adjective: handsome, smart (for men)"],
["顺便","shùn biàn","Adverb: on the way, in passing by"],
["顺利","shùn lì","Adjective: smoothly"],
["顺序","shùn xù","Noun: sequence, order"],
["说明","shuō míng","Noun: explanation, illustration; Verb: to explain, to illustrate"],
["硕士","shuò shì","Noun: master's degree"],
["死","sǐ","Noun: death; Verb: to die; Adjective: dead"],
["速度","sù dù","Noun: speed"],
["塑料袋","sù liào dài","Noun: plastic bag"],
["算","suàn","Verb: to calculate"],
["酸","suān","Adjective: sour"],
["随便","suí biàn","Adjective: random; Adverb: as one wishes"],
["随着","suí zhe","Preposition: along with, in the wake of"],
["孙子","sūn zi","Noun: grandson"],
["所有","suǒ yǒu","Verb: to possess, to own; Adjective: all"],
["台","tái","Noun: desk, platform; Measure Word: for vehicles, machinese, etc."],
["抬","tái","Verb: to lift up, to raise, to carry"],
["态度","tài du","Noun: manner, attitude"],
["谈","tán","Verb: to talk"],
["弹钢琴","tán gāng qín","Verb: to play the piano"],
["趟","tàng","Measure Word: for number of trips or runs made"],
["躺","tǎng","Verb: to lie (down), to recline"],
["汤","tāng","Noun: soup"],
["讨论","tǎo lùn","Noun: discussion; Verb: to discuss"],
["讨厌","tǎo yàn","Verb: to hate; Adjective: disgusting, nasty"],
["特点","tè diǎn","Noun: characteristic feature"],
["提供","tí gōng","Verb: to offer, to supply, to provide"],
["提前","tí qián","Verb: to bring forward, to advance"],
["提醒","tí xǐng","Verb: to remind, to call attention to"],
["填空","tián kòng","Verb: to fill in (questionnaire, etc.)"],
["条件","tiáo jiàn","Noun: condition, circumstances"],
["挺","tǐng","Verb: to stick out, to stand straight; Adverb: quite, very, rather; Measure Word: for machine guns"],
["停止","tíng zhǐ","Verb: to stop, to halt"],
["通过","tōng guò","Verb: to pass through, to get through; Preposition: via, by"],
["同情","tóng qíng","Noun: sympathy, compassion; Verb: to sympathize"],
["通知","tōng zhī","Noun: notice; Verb: to notify, to inform"],
["推","tuī","Verb: to push"],
["推迟","tuī chí","Verb: to postpone, to defer"],
["脱","tuō","Verb: to take off, to shed"],
["袜子","wà zi","Noun: socks, stockings"],
["完全","wán quán","Adjective: complete, whole, entire"],
["往","wǎng","Verb: to go; Preposition: towards, to"],
["网球","wǎng qiú","Noun: tennis"],
["往往","wǎng wǎng","Adverb: often"],
["网站","wǎng zhàn","Noun: website"],
["味道","wèi dào","Noun: taste, flavour"],
["危险","wēi xiǎn","Noun: danger; Adjective: dangerous"],
["温度","wēn dù","Noun: temperature"],
["文章","wén zhāng","Noun: article, essay"],
["握手","wò shǒu","Verb: to shake hands"],
["无","wú","Adverb: not"],
["误会","wù huì","Noun: misunderstanding; Verb: to misunderstand"],
["无聊","wú liáo","Adjective: boring, bored"],
["无论","wú lùn","Conjunction: no matter how/what"],
["污染","wū rǎn","Noun: pollution, contamination; Verb: to pollute, to contaminate"],
["西红柿","xī hóng shì","Noun: tomato"],
["洗衣机","xǐ yī jī","Noun: washing machine"],
["吸引","xī yǐn","Verb: to attract (interest, customers, etc.)"],
["咸","xián","Adjective: salty"],
["现代","xiàn dài","Noun: modern times, the contemporary age"],
["羡慕","xiàn mù","Verb: to envy, to admire"],
["限制","xiàn zhì","Noun: restriction, limit; Verb: to restrict, to limit"],
["响","xiǎng","Noun: sound, noise; Verb: to make a sound; Adjective: loud, noisy"],
["香","xiāng","Adjective: fragrang"],
["相反","xiāng fǎn","Adjective: opposite, contrary"],
["详细","xiáng xì","Adjective: detailed"],
["效果","xiào guǒ","Noun: effect, result"],
["笑话","xiào hua","Noun: joke"],
["小说","xiǎo shuō","Noun: novel, fiction"],
["消息","xiāo xi","Noun: news, information"],
["辛苦","xīn kǔ","Adjective: hard, toilsome"],
["心情","xīn qíng","Noun: mood, state of mind"],
["信任","xìn rèn","Noun: trust; Verb: to trust"],
["信心","xìn xīn","Noun: confidence, faith"],
["信用卡","xìn yòng kǎ","Noun: credit card"],
["行","xíng","Verb: to walk, to go; Adjective: capable, competent; Saying: OK"],
["醒","xǐng","Verb: to wake up"],
["性别","xìng bié","Noun: gender, sex"],
["兴奋","xīng fèn","Noun: excitement; Adjective: excited"],
["幸福","xìng fú","Noun: happiness; Adjective: happy"],
["性格","xìng gé","Noun: nature, temperament, character"],
["修","xiū","Verb: to mend, to repair"],
["许多","xǔ duō","Adjective: many, a lot of"],
["血","xuè","Noun: blood"],
["呀","ya","Particle: expressing surprise or doubt"],
["牙膏","yá gāo","Noun: toothpaste"],
["压力","yā lì","Noun: preassure"],
["亚洲","Yà zhōu","Noun: Asia"],
["盐","yán","Noun: salt"],
["演出","yǎn chū","Noun: performance, show; Verb: to perform, to put ona show"],
["严格","yán gé","Adjective: strict, rigorous"],
["研究生","yán jiū shēng","Noun: graduate, postgraduate or research student"],
["演员","yǎn yuán","Noun: performer, actor"],
["严重","yán zhòng","Adjective: grave, serious, critical"],
["养成","yǎng chéng","Verb: to cultivate, to form, to acquire"],
["阳光","yáng guāng","Noun: sunshine"],
["样子","yàng zi","Noun: appearance, manner"],
["邀请","yāo qǐng","Noun: invitation; Verb: to invite"],
["钥匙","yào shi","Noun: key"],
["页","yè","Noun: page, leaf; Measure Word: for a page"],
["也许","yě xǔ","Adverb: perhaps, maybe"],
["叶子","yè zi","Noun: leaf"],
["亿","yì","Number: 100 million"],
["以","yǐ","Preposition: because of, so as to, in order to"],
["意见","yì jiàn","Noun: opinion, view, objection"],
["一切","yí qiè","Pronoun: all, everything"],
["艺术","yì shù","Noun: art"],
["因此","yīn cǐ","Conjunction: thus, consequently"],
["饮料","yǐn liào","Noun: drink, beverage"],
["引起","yǐn qǐ","Verb: to give rise to, to lead to"],
["印象","yìn xiàng","Noun: impression"],
["赢","yíng","Verb: to win, to beat"],
["硬","yìng","Adjective: hard, stiff, firm"],
["勇敢","yǒng gǎn","Adjective: brave, courageous"],
["永远","yǒng yuǎn","Adverb: forever, ever"],
["由","yóu","Preposition: due to, because of, by, from"],
["优点","yōu diǎn","Noun: merit, advantage, strong point"],
["友好","yǒu hǎo","Adjective: friendly"],
["幽默","yōu mò","Noun: humor; Adjective: humorous"],
["尤其","yóu qí","Adverb: especially, particularly"],
["有趣","yǒu qù","Adjective: interesting"],
["优秀","yōu xiù","Adjective: outstanding, excellent"],
["友谊","yǒu yì","Noun: friendship"],
["由于","yóu yú","Preposition: due to, because of"],
["与","yǔ","Conjunction: and, with"],
["语法","yǔ fǎ","Noun: grammar"],
["愉快","yú kuài","Adjective: happy, cheerful"],
["羽毛球","yǔ máo qiú","Noun: badminton"],
["于是","yú shì","Conjunction: as a result, consequently"],
["预习","yù xí","Verb: to prepare for (a lesson)"],
["语言","yǔ yán","Noun: language"],
["圆","yuán","Noun: circle; Adjective: circular, round"],
["原来","yuán lái","Adjective: former, original; Adverb: as it turns out"],
["原谅","yuán liàng","Verb: to excuse, to forgive"],
["原因","yuán yīn","Noun: reason, cause"],
["阅读","yuè dú","Noun: reading; Verb: to read"],
["约会","yuē huì","Noun: appointment, engagement, date"],
["允许","yǔn xǔ","Verb: to permit, to allow"],
["杂志","zá zhì","Noun: magazine"],
["咱们","zán men","Pronoun: we, us"],
["暂时","zàn shí","Adjective: temporary"],
["脏","zāng","Adjective: dirty"],
["责任","zé rèn","Noun: duty, responsibility"],
["增加","zēng jiā","Verb: to increase, to raise"],
["增长","zēng zhǎng","Noun: increase, growth; Verb: to increase, to grow"],
["窄","zhǎi","Adjective: narrow"],
["招聘","zhāo pìn","Noun: recruitment, job advertisement; Verb: to recruit"],
["真正","zhēn zhèng","Adjective: genuine, real, true"],
["正常","zhèng cháng","Adjective: regular, normal, ordinary"],
["正好","zhèng hǎo","Adverb: just right, just at the right time"],
["整理","zhěng lǐ","Verb: to arrange, to tidy up"],
["证明","zhèng míng","Noun: proof, certificate, testimonial; Verb: to prove, to testify"],
["整齐","zhěng qí","Adjective: neat, tidy, in good order"],
["正确","zhèng què","Adjective: correct, proper"],
["正式","zhèng shì","Adjective: formal, official"],
["指","zhǐ","Noun: finger; Verb: to point at or to, to indicate"],
["之","zhī","Pronoun: I, he, she it, ...; Particle: similar to 的"],
["只","zhī","Measure Word: for birds and animals, a pair of things, parts of the body, etc."],
["支持","zhī chí","Noun: support, backing; Verb: to support, to back"],
["值得","zhí dé","Verb: to be worth, to deserve"],
["只好","zhǐ hǎo","Adverb: have to"],
["直接","zhí jiē","Adjective: direct, immediate"],
["质量","zhì liàng","Noun: quality"],
["至少","zhì shǎo","Adverb: at least"],
["知识","zhī shi","Noun: knowledge"],
["植物","zhí wù","Noun: plant"],
["只要","zhǐ yào","Conjunction: if only, as long as"],
["职业","zhí yè","Noun: occupation, profession"],
["制造","zhì zào","Verb: to make, to manufacture"],
["重点","zhòng diǎn","Noun: emphasis, focal point, priority"],
["重视","zhòng shì","Verb: to value, to attach importance to"],
["中文","Zhōng wén","Noun: Chinese language"],
["周围","zhōu wéi","Noun: surroundings, environment; Adverb: around, about"],
["猪","zhū","Noun: pig"],
["主动","zhǔ dòng","Verb: to take the initiative; Adjective: active"],
["祝贺","zhù hè","Noun: congratulations; Verb: to congratulate"],
["逐渐","zhú jiàn","Adverb: gradually"],
["著名","zhù míng","Adjective: famous, well-known"],
["主意","zhǔ yi","Noun: idea, plan, decision"],
["赚","zhuàn","Verb: to earn, to make a profit"],
["专门","zhuān mén","Adjective: special, specialized; Adverb: specialized"],
["专业","zhuān yè","Noun: speciality, major, field of study"],
["撞","zhuàng","Verb: to hit, to bump against, to collide, to run into"],
["准确","zhǔn què","Adjective: accurate, precise, exact"],
["准时","zhǔn shí","Adjective: on time, punctual"],
["自然","zì rán","Noun: nature; Adjective: natural"],
["仔细","zǐ xì","Adjective: careful, attentive, cautious"],
["总结","zǒng jié","Noun: summary; Verb: to sum up"],
["租","zū","Verb: to rent, to hire"],
["组成","zǔ chéng","Noun: composition; Verb: to form, to compose, to constitute"],
["组织","zǔ zhī","Noun: organisation; Verb: to organize"],
["嘴","zuǐ","Noun: mouth"],
["最好","zuì hǎo","Adverb: it would be best, had better"],
["最后","zuì hòu","Time: finally, at last"],
["尊重","zūn zhòng","Noun: respect, esteem; Verb: to respect, to honor"],
["座","zuò","Noun: seat; Measure Word: for cities, buildings, mountains, etc."],
["做生意","zuò shēng yi","Verb: to do business"],
["座位","zuò wèi","Noun: seat, place"],
["作者","zuò zhě","Noun: author, writer"]
]};

