dictionaries["hsk5"] = {
	"name" : "HSK5 vocabulary (1300 words) (English)",
	"desc" : "Hànyǔ Shuǐpíng Kǎoshì (HSK) (汉语水平考试)",
	"link" : "http://www.wohok.com",
	"language" : "zh-simp",
	"words": [
["唉","āi","Particle: uh (sigh)"],
["爱护","ài hù","Verb: to cherish, to take good care of"],
["爱惜","ài xī","Verb: to cherish, to treasure"],
["爱心","ài xīn","Noun: tender feelings; affections"],
["岸","àn","Noun: shore, beach, coast"],
["安慰","ān wèi","Noun: comfort, consolation; Verb: to comfort, to console"],
["安装","ān zhuāng","Noun: installation; Verb: to install, to mount"],
["把握","bǎ wò","Noun: assurance; Verb: to grasp, to hold"],
["摆","bǎi","Noun: pendulum; Verb: to put, to place, to arragne"],
["办理","bàn lǐ","Verb: to handle, to conduct"],
["班主任","bān zhǔ rèn","Noun: teacher in charge of a class"],
["棒","bàng","Noun: stick, club; Adjective: strong, capable, good; Measure Word: for legs of relay race"],
["傍晚","bàng wǎn","Time: towards evening, at nightfall"],
["薄","báo","Adjective: thin"],
["宝贝","bǎo bèi","Noun: darling, baby"],
["保持","bǎo chí","Verb: to keep, to maintain, to preserve"],
["保存","bǎo cún","Verb: to conserve, to keep, to save (IT)"],
["报告","bào gào","Noun: report, speech, talk; Verb: to report"],
["宝贵","bǎo guì","Adjective: valuable, precious"],
["包裹","bāo guǒ","Noun: parcel, package; Verb: to wrap up"],
["包含","bāo hán","Verb: to contain, to emobdy, to include"],
["保留","bǎo liú","Noun: reservation; Verb: to reserve, to hold back"],
["保险","bǎo xiǎn","Noun: insurance; Verb: to insure; Adjective: safe, secure"],
["包子","bāo zi","Noun: steamed stuffed bun"],
["背","bèi","Noun: back; Verb: to learn by heart"],
["悲观","bēi guān","Adjective: pessimistic"],
["背景","bèi jǐng","Noun: background, context"],
["被子","bèi zi","Noun: quilt"],
["本科","běn kē","Noun: Bachelor course"],
["本领","běn lǐng","Noun: skill, ability, capability"],
["本质","běn zhì","Noun: essence, nature"],
["彼此","bǐ cǐ","Pronoun: each other, one another"],
["毕竟","bì jìng","Adverb: after all, in the end"],
["比例","bǐ lì","Noun: proportion, scale"],
["避免","bì miǎn","Verb: to avoid, to prevent"],
["必然","bì rán","Adjective: inevitable, certain"],
["比如","bǐ rú","Adverb: for example"],
["必需","bì xū","Verb: to really need, to be essential, must"],
["必要","bì yào","Adjective: necessary, essential"],
["便","biàn","Verb: to relieve oneself; Adjective: convenient, handy; Adverb: then, in that case"],
["编辑","biān jí","Noun: editor, compiler; Verb: to edit, to compile"],
["辩论","biàn lùn","Noun: debate, argument; Verb: to debate, to argue"],
["鞭炮","biān pào","Noun: firecrackers"],
["标点","biāo diǎn","Noun: punctuation, punctuation mark"],
["表面","biǎo miàn","Noun: surface, outside, appearance"],
["表明","biǎo míng","Verb: to show, to indicate, to make clear"],
["表情","biǎo qíng","Noun: expression"],
["表现","biǎo xiàn","Verb: to show, to express, to display"],
["标志","biāo zhì","Noun: symbol, sign; Verb: to symbolize, to indicate"],
["丙","bǐng","Number: third(ly)"],
["病毒","bìng dú","Noun: virus"],
["玻璃","bō li","Noun: glass"],
["博物馆","bó wù guǎn","Noun: museum"],
["脖子","bó zi","Noun: neck"],
["布","bù","Noun: cloth"],
["不安","bù ān","Adjective: disturbed, uneasy"],
["不必","bú bì","Verb: does not have to"],
["补充","bǔ chōng","Noun: supplement; Verb: to supplement, to complement; Adjective: additional, supplementary"],
["不得了","bù dé liǎo","Adjective: disastrous, terrible; Adverb: extremely, terribly"],
["不断","bú duàn","Adverb: continuous, unceasing"],
["不好意思","bù hǎo yì si","Verb: to feel embarrassed; Saying: excuse me, sorry"],
["不见得","bú jiàn dé","Adverb: not necessarily, not likely"],
["部门","bù mén","Noun: department, branch"],
["不免","bù miǎn","Adverb: inevitably"],
["不耐烦","bú nài fán","Noun: impatience; Adjective: impatient"],
["不然","bù rán","Conjunction: otherwise"],
["不如","bù rú","Verb: not as good as"],
["不要紧","bú yào jǐn","Saying: it doesn't matter, never mind"],
["步骤","bù zhòu","Noun: step, move, measure"],
["不足","bù zú","Noun: shortcomings; Adjective: insufficient, not enough"],
["踩","cǎi","Verb: to stamp on, to step, to press a pedal"],
["财产","cái chǎn","Noun: property, possession"],
["采访","cǎi fǎng","Verb: to interview, to gather news"],
["彩虹","cǎi hóng","Noun: rainbow"],
["采取","cǎi qǔ","Verb: to carry out, to adopt, to take"],
["残疾","cán jí","Noun: disability, deformity; Adjective: disabled, handicapped"],
["参考","cān kǎo","Noun: consultation, reference; Verb: to consult, to refer to"],
["惭愧","cán kuì","Adjective: ashamed"],
["餐厅","cān tīng","Noun: restaurant"],
["参与","cān yù","Verb: to participate in, to attach oneself to"],
["操场","cāo chǎng","Noun: playground, sports field"],
["操心","cāo xīn","Verb: to worry about, to take pains"],
["册","cè","Noun: book, booklet; Measure Word: for books"],
["厕所","cè suǒ","Noun: toilet"],
["测验","cè yàn","Noun: test, examination; Verb: to test"],
["曾经","céng jīng","Adverb: once, former, previously"],
["插","chā","Verb: to insert, to stick in"],
["差别","chā bié","Noun: difference"],
["叉子","chā zi","Noun: fork"],
["拆","chāi","Verb: open, tear down"],
["产品","chǎn pǐn","Noun: product, goods"],
["产生","chǎn shēng","Verb: to produce, to come about"],
["常识","cháng shí","Noun: common sense, general knowledge"],
["长途","cháng tú","Noun: long distance"],
["朝","cháo","Noun: dynasty, imperial or royal court; Preposition: towards, facing"],
["炒","chǎo","Verb: to fry"],
["抄","chāo","Verb: to copy, to plagiarize"],
["朝代","cháo dài","Noun: dynasty"],
["吵架","chǎo jià","Noun: quarrel; Verb: to quarrel"],
["彻底","chè dǐ","Adjective: thorough"],
["车库","chē kù","Noun: garage"],
["车厢","chē xiāng","Noun: carriage"],
["趁","chèn","Verb: to take advantage of"],
["沉默","chén mò","Noun: silence, hush; Verb: to keep silent; Adjective: silent, uncommunicative"],
["乘","chéng","Verb: to ride on, to multiply"],
["称","chēng","Verb: to weigh, to name, to state"],
["承担","chéng dān","Verb: to undertake, to shoulder, to take (responsibility, etc.)"],
["程度","chéng dù","Noun: degree, extent, level"],
["成分","chéng fèn","Noun: ingredient, component"],
["成果","chéng guǒ","Noun: result, achievement, gain"],
["称呼","chēng hu","Noun: name, term of address; Verb: to address sb., to call sb. (a name)"],
["成就","chéng jiù","Noun: accomplishment, achievement"],
["诚恳","chéng kěn","Adjective: sincere, honest"],
["成立","chéng lì","Verb: to establish, to set up, to found"],
["承认","chéng rèn","Noun: recognition; Verb: to admit, to recognize, to acknowledge"],
["承受","chéng shòu","Verb: to bear, to endure, to receive"],
["程序","chéng xù","Noun: procedure, process, program (IT)"],
["成语","chéng yǔ","Noun: idiom, proverb"],
["称赞","chēng zàn","Verb: to praise, to acclaim, to commend"],
["成长","chéng zhǎng","Verb: to grow up, to mature"],
["翅膀","chì bǎng","Noun: wing"],
["吃亏","chī kuī","Verb: to suffer losses, to lose out"],
["持续","chí xù","Verb: to continue, to persist"],
["池子","chí zi","Noun: pond"],
["尺子","chǐ zi","Noun: ruler"],
["冲","chōng","Verb: to flush, to head for"],
["充电器","chōng diàn qì","Noun: battery charger"],
["充分","chōng fèn","Adjective: ample, full, abundant"],
["重复","chóng fù","Verb: to repeat, to duplicate"],
["充满","chōng mǎn","Verb: brimming with, full of"],
["宠物","chǒng wù","Noun: pet"],
["臭","chòu","Adjective: smelly"],
["丑","chǒu","Noun: clown; Adjective: ugly, bad-looking"],
["抽屉","chōu ti","Noun: drawer"],
["抽象","chōu xiàng","Adjective: abstract"],
["除","chú","Verb: to divide, to exclude; Preposition: except for"],
["出版","chū bǎn","Verb: to publish"],
["除非","chú fēi","Conjunction: only if, unless"],
["初级","chū jí","Adjective: primary, elementary"],
["出口","chū kǒu","Noun: exit, export"],
["处理","chǔ lǐ","Verb: to deal with, to handle, to cope with"],
["出色","chū sè","Adjective: outstanding, remarkable"],
["除夕","chú xī","Noun: New Year's Eve"],
["出席","chū xí","Verb: to attend, to be present"],
["传播","chuán bō","Verb: to spread, to propagate, to disseminate"],
["传递","chuán dì","Verb: to pass on to, to transfer"],
["传染","chuán rǎn","Verb: to infect, to be contagious"],
["传说","chuán shuō","Noun: legend, folklore; Verb: it is said, that..."],
["传统","chuán tǒng","Noun: tradition; Adjective: traditional"],
["闯","chuǎng","Verb: to rush, to break through, to charge"],
["窗帘","chuāng lián","Noun: window curtains"],
["创造","chuàng zào","Noun: creation; Verb: to create, to produce"],
["吹","chuī","Verb: to blow, to boast, to fail"],
["磁带","cí dài","Noun: magnetic tape"],
["刺激","cì jī","Noun: stimulus, provocation; Verb: to provoke, to stimulate, to excite"],
["此外","cǐ wài","Conjunction: besides, moreover"],
["次要","cì yào","Adjective: secondary, subordinate"],
["辞职","cí zhí","Verb: to resign"],
["从此","cóng cǐ","Conjunction: from now on"],
["从而","cóng ér","Conjunction: thus, thereby"],
["匆忙","cōng máng","Adjective: hasty, hurried"],
["从前","cóng qián","Time: previously, formerly"],
["从事","cóng shì","Verb: to engage in, to do (formal)"],
["醋","cù","Noun: vinegar"],
["促进","cù jìn","Verb: to promote, to advance"],
["促使","cù shǐ","Verb: to urge, to push, to promote"],
["催","cuī","Verb: to urge, to press"],
["存","cún","Verb: to deposit, to keep"],
["存在","cún zài","Verb: to exist"],
["措施","cuò shī","Noun: measure, step"],
["错误","cuò wù","Noun: error, mistake"],
["达到","dá dào","Verb: to achieve, to reach, to attain"],
["大方","dà fang","Adjective: generous, of good taste"],
["打工","dǎ gōng","Noun: a part time job; Verb: to work (temporary or casual)"],
["打交道","dǎ jiāo dao","Verb: have dealings with"],
["打喷嚏","dǎ pēn tì","Verb: to sneeze"],
["打听","dǎ ting","Verb: to ask about, to inquire about, to nose into"],
["大象","dà xiàng","Noun: elephant"],
["大型","dà xíng","Adjective: large-scale"],
["答应","dā ying","Verb: to agree, to promise, to respond"],
["打招呼","dǎ zhāo hu","Verb: to greet sbd., to give prior notice"],
["呆","dāi","Verb: to stay; Adjective: dull, foolish, stupid"],
["贷款","dài kuǎn","Noun: loan; Verb: to provide a loan"],
["待遇","dài yù","Noun: treatment, pay, salary"],
["淡","dàn","Adjective: mild, (rather) tasteless, light in color"],
["单纯","dān chún","Adjective: pure, simple"],
["单调","dān diào","Adjective: monotonous, dull"],
["单独","dān dú","Adjective: alone, solo"],
["担任","dān rèn","Verb: to hold the post of, to serve as"],
["单位","dān wèi","Noun: unit"],
["耽误","dān wu","Verb: to delay"],
["胆小鬼","dǎn xiǎo guǐ","Noun: coward"],
["单元","dān yuán","Noun: unit, cell, entrance number"],
["挡","dǎng","Verb: to block, to hinder, to obstruct"],
["当代","dāng dài","Time: present, nowadays"],
["倒","dào","Verb: to pour, to reverse; Adverb: on the contrary, instead"],
["岛","dǎo","Noun: island"],
["到达","dào dá","Verb: to arrive, to reach"],
["道德","dào dé","Noun: morality, ethics"],
["道理","dào lǐ","Noun: principle, reason, argument"],
["倒霉","dǎo méi","Verb: to have bad luck"],
["导演","dǎo yǎn","Noun: director (film, etc.); Verb: to direct"],
["导致","dǎo zhì","Verb: to lead to, to create, to bring about"],
["等待","děng dài","Verb: to wait for, to await"],
["等候","děng hòu","Verb: to wait"],
["登记","dēng jì","Verb: to register"],
["登机牌","dēng jī pái","Noun: boarding pass"],
["等于","děng yú","Verb: to equal, to amount to"],
["递","dì","Verb: to pass, to hand over"],
["滴","dī","Verb: to drip, to drop; Measure Word: for a drop"],
["地道","dì dao","Adjective: authentic, genuine, real"],
["地理","dì lǐ","Noun: geography"],
["地区","dì qū","Noun: region, district, area"],
["的确","dí què","Adverb: really, indeed"],
["敌人","dí rén","Noun: enemy"],
["地毯","dì tǎn","Noun: carpet"],
["地位","dì wèi","Noun: position, status"],
["地震","dì zhèn","Noun: earthquake"],
["电池","diàn chí","Noun: battery, electric cell"],
["电台","diàn tái","Noun: broadcasting station, radio station"],
["点头","diǎn tóu","Verb: to nod"],
["点心","diǎn xin","Noun: light refreshments, Dimsum (Cantonese)"],
["钓","diào","Verb: to fish"],
["顶","dǐng","Noun: top, roof; Verb: to carry on the head; Adverb: most, extremely, highly; Measure Word: for caps, hats, tents, etc."],
["丁","dīng","Number: fourth"],
["冻","dòng","Noun: jelly; Verb: to freeze, to feel very cold"],
["洞","dòng","Noun: cave, hole"],
["动画片","dòng huà piàn","Noun: cartoon, animation"],
["逗","dòu","Verb: to stay, to pause, to tease"],
["豆腐","dòu fu","Noun: tofu"],
["度过","dù guò","Verb: to spend, to pass"],
["独立","dú lì","Noun: independence; Verb: to stand alone; Adjective: independent"],
["独特","dú tè","Adjective: unique, distinct"],
["短信","duǎn xìn","Noun: text message"],
["堆","duī","Noun: pile, stack, heap; Measure Word: for piles of things"],
["对比","duì bǐ","Noun: contrast, comparison; Verb: to contrast, to compare"],
["对待","duì dài","Noun: treatment; Verb: to treat, to approach"],
["对方","duì fāng","Noun: counterpart, the other side"],
["对手","duì shǒu","Noun: opponent, rival"],
["对象","duì xiàng","Noun: lover, partner, target, object"],
["对于","duì yú","Pronoun: regarding, as far as sth. is concerned"],
["吨","dūn","Measure Word: for a ton"],
["蹲","dūn","Verb: to squat"],
["躲藏","duǒ cáng","Verb: to hide oneself"],
["多亏","duō kuī","Adverb: luckily, thanks to"],
["多余","duō yú","Adjective: unnecessary, surplus, needless"],
["恶劣","è liè","Adjective: very bad, vile, disgusting"],
["发表","fā biǎo","Verb: to issue, to publish"],
["发愁","fā chóu","Verb: to worry, to be anxious"],
["发达","fā dá","Verb: to develop; Adjective: developed (country, etc.)"],
["发抖","fā dǒu","Verb: to shiver, to shudder, to tremble"],
["发挥","fā huī","Verb: to develop (skill, ability, idea, etc.), to give play to"],
["罚款","fá kuǎn","Noun: fine, penalty; Verb: to fine"],
["发明","fā míng","Noun: invention; Verb: to invent"],
["发票","fā piào","Noun: invoice, receipt"],
["发言","fā yán","Noun: statement; Verb: to speak, to make a speech"],
["法院","fǎ yuàn","Noun: court of law, court"],
["翻","fān","Verb: to turn over, to flip over"],
["反而","fǎn ér","Adverb: instead, on the contrary"],
["反复","fǎn fù","Adverb: repeatedly"],
["繁荣","fán róng","Adjective: flourishing, prosperous, booming"],
["凡是","fán shì","Adverb: every, any, all"],
["反应","fǎn yìng","Noun: reaction, response; Verb: to react, to respond"],
["反正","fǎn zhèng","Adverb: anyway, whatever happens"],
["方","fāng","Noun: square, direction, side; Measure Word: for square things"],
["妨碍","fáng ài","Verb: to hinder, to obstruct"],
["方案","fāng àn","Noun: plan, program, scheme"],
["房东","fáng dōng","Noun: landlord"],
["仿佛","fǎng fú","Adverb: to seem as if"],
["方式","fāng shì","Noun: way, pattern, manner"],
["放松","fàng sōng","Verb: to relax, to loosen"],
["肺","fèi","Noun: lung"],
["非","fēi","Adjective: wrong, mistaken; Adverb: not, non-, un-"],
["废话","fèi huà","Saying: nonsense, useless statement"],
["费用","fèi yong","Noun: expenses, cost"],
["肥皂","féi zào","Noun: soap"],
["分别","fēn bié","Noun: difference; Verb: to leave each other, to distinguish; Adverb: separate"],
["分布","fēn bù","Verb: to distribute, to be distributed"],
["奋斗","fèn dòu","Verb: to fight for, to strive for"],
["纷纷","fēn fēn","Adverb: one after another"],
["愤怒","fèn nù","Adjective: angry"],
["分配","fēn pèi","Verb: to assign, to allocate"],
["分析","fēn xī","Noun: analysis; Verb: to analyze"],
["讽刺","fěng cì","Noun: irony, sarcasm; Verb: to mock"],
["风格","fēng gé","Noun: style"],
["疯狂","fēng kuáng","Noun: madness; Adjective: crazy, mad"],
["风俗","fēng sú","Noun: (social) custom"],
["风险","fēng xiǎn","Noun: risk,l venture"],
["否定","fǒu dìng","Noun: negation; Verb: to negate, to deny"],
["否认","fǒu rèn","Verb: to deny"],
["幅","fú","Measure Word: for pictures, paintings, textiles, etc."],
["扶","fú","Verb: to help (sb. up)"],
["服从","fú cóng","Verb: to obey, to submit"],
["辅导","fǔ dǎo","Noun: coaching; Verb: to tutor, to coach"],
["付款","fù kuǎn","Noun: payment; Verb: to pay"],
["妇女","fù nǚ","Noun: woman"],
["复制","fù zhì","Verb: to copy, to reproduce"],
["服装","fú zhuāng","Noun: clothing, dress"],
["盖","gài","Noun: cover; Verb: to cover"],
["改革","gǎi gé","Noun: reform; Verb: to reform"],
["改进","gǎi jìn","Noun: improvement; Verb: to improve"],
["概括","gài kuò","Noun: summary; Verb: to summarize; to generalize"],
["概念","gài niàn","Noun: concept, idea"],
["改善","gǎi shàn","Noun: improvement; Verb: to improve"],
["改正","gǎi zhèng","Noun: correction; Verb: to correct, to amend"],
["干脆","gān cuì","Adjective: clear-cut, straightforward; Adverb: simply, you might as well"],
["干活儿","gàn huó r","Verb: to work (often hard, manual work)"],
["感激","gǎn jī","Verb: to feel grateful, to be thankful"],
["赶紧","gǎn jǐn","Adverb: at once, losing no time"],
["赶快","gǎn kuài","Adverb: at once, immediately"],
["感受","gǎn shòu","Noun: feeling, perception; Verb: to sense, to feel"],
["感想","gǎn xiǎng","Noun: impressions, reflections"],
["钢铁","gāng tiě","Noun: steel"],
["搞","gǎo","Verb: to do, to make"],
["告别","gào bié","Verb: to leave, to say good-bye to"],
["高档","gāo dàng","Adjective: top grade"],
["高速公路","gāo sù gōng lù","Noun: highway"],
["隔壁","gé bì","Place: next door"],
["个别","gè bié","Adjective: exceptional, very few, individual"],
["胳膊","gē bo","Noun: arm"],
["革命","gé mìng","Noun: revolution"],
["个人","gè rén","Noun: individual; Adjective: individual"],
["格外","gé wài","Adverb: especially, particularly"],
["个性","gè xìng","Noun: personality, character"],
["鸽子","gē zi","Noun: pigeon"],
["各自","gè zì","Adverb: each, respective"],
["根","gēn","Noun: root, origin; Measure Word: for long, slender objects"],
["根本","gēn běn","Noun: foundation, root; Adjective: fundamental, simply, basic"],
["更加","gèng jiā","Adverb: more, even more"],
["公布","gōng bù","Verb: to announce, to make public"],
["工厂","gōng chǎng","Noun: factory"],
["工程师","gōng chéng shī","Noun: engineer"],
["功夫","gōng fu","Noun: time, skill, labor, workmanship, kung fu"],
["公开","gōng kāi","Verb: to publish, to make public; Adjective: public"],
["功能","gōng néng","Noun: function, feature"],
["公平","gōng píng","Adjective: fair, impartial"],
["工人","gōng rén","Noun: worker"],
["贡献","gòng xiàn","Noun: contribution; Verb: to contribute, to dedicate"],
["工业","gōng yè","Noun: industry"],
["公寓","gōng yù","Noun: block of flats"],
["公元","gōng yuán","Noun: Christian era"],
["公主","gōng zhǔ","Noun: princess"],
["构成","gòu chéng","Verb: to compose, to constitute, to configure (IT)"],
["沟通","gōu tōng","Verb: to communicate"],
["古代","gǔ dài","Time: ancient times"],
["古典","gǔ diǎn","Adjective: classical"],
["固定","gù dìng","Verb: to fasten, to fix; Adjective: fixed, set, regular"],
["姑姑","gū gu","Noun: aunt (paternal)"],
["古老","gǔ lǎo","Adjective: ancient, age-old"],
["姑娘","gū niang","Noun: girl, young woman, daughter"],
["股票","gǔ piào","Noun: share, stock"],
["固体","gù tǐ","Noun: solid (body)"],
["骨头","gǔ tou","Noun: bone, strong character"],
["鼓舞","gǔ wǔ","Noun: encouragement; Verb: to inspire, to animate"],
["雇佣","gù yōng","Verb: to employ, to hire"],
["挂号","guà hào","Verb: to register"],
["乖","guāi","Adjective: obedient, well-behaved, clever, good"],
["怪不得","guài bu de","Conjunction: no wonder so that is why"],
["拐弯","guǎi wān","Verb: to turn a corner, to change direction"],
["官","guān","Noun: officer, government official"],
["关闭","guān bì","Verb: to close, to shut"],
["观察","guān chá","Noun: observation; Verb: to observe, to watch, to survey"],
["观点","guān diǎn","Noun: point of view, viewpoint, standpoint"],
["关怀","guān huái","Noun: care, solicitude; Verb: to care for, to show solicitude for"],
["冠军","guàn jūn","Noun: champion"],
["观念","guān niàn","Noun: concept, idea, thought"],
["罐头","guàn tou","Noun: tin, can"],
["管子","guǎn zi","Noun: tube, pipe"],
["广场","guǎng chǎng","Noun: public square"],
["广大","guǎng dà","Adjective: vast, extensive, widespread"],
["广泛","guǎng fàn","Adjective: extensive, wide ranging"],
["光滑","guāng huá","Adjective: smooth, sleek, glossy"],
["光临","guāng lín","Verb: to visit as honorable guest"],
["光明","guāng míng","Noun: light, radiance; Adjective: light, bright"],
["光盘","guāng pán","Noun: CD, DVD"],
["光荣","guāng róng","Noun: honor, glory; Adjective: glorious, honorable"],
["规矩","guī ju","Noun: rule, custom, manner, practices"],
["规律","guī lǜ","Noun: law, regular pattern"],
["规模","guī mó","Noun: scale, scope, size, extent"],
["柜台","guì tái","Noun: (sales) counter, bar"],
["规则","guī zé","Noun: rule, regulation"],
["滚","gǔn","Verb: to boil, to roll"],
["锅","guō","Noun: pot, pan"],
["过分","guò fèn","Adjective: excessive, undue"],
["国籍","guó jí","Noun: nationality, citizenship"],
["过敏","guò mǐn","Noun: allergy; Verb: to be allergic"],
["过期","guò qī","Verb: to expire, to exceed the time limit"],
["国庆节","Guó qìng jié","Noun: National Day (October 1st)"],
["果实","guǒ shí","Noun: fruits, gains"],
["哈","hā","Onomatope: haha, laughter"],
["海关","hǎi guān","Noun: customs"],
["海鲜","hǎi xiān","Noun: seafood"],
["喊","hǎn","Verb: to shout, to yell"],
["行业","háng yè","Noun: business, industry, profession"],
["豪华","háo huá","Adjective: luxurious"],
["好奇","hào qí","Adjective: curious, inquisitive"],
["何必","hé bì","Adverb: there is no need to"],
["合法","hé fǎ","Adjective: legal, legitimate"],
["何况","hé kuàng","Preposition: let alone"],
["合理","hé lǐ","Adjective: reasonable, rational"],
["和平","hé píng","Noun: peace"],
["合同","hé tong","Noun: contract"],
["核心","hé xīn","Noun: core"],
["合影","hé yǐng","Noun: group photo"],
["合作","hé zuò","Noun: cooperation; Verb: to cooperate, to work together"],
["恨","hèn","Noun: hate; Verb: to hate"],
["横","héng","Adjective: horizontal, across"],
["后果","hòu guǒ","Noun: consequence, aftermath"],
["壶","hú","Noun: pot; Measure Word: for bottled liquid"],
["蝴蝶","hú dié","Noun: butterfly"],
["忽视","hū shì","Verb: to neglect, to ignore, to overlook"],
["胡说","hú shuō","Verb: to talk nonsense"],
["胡同","hú tòng","Noun: lane, alley"],
["糊涂","hú tu","Adjective: confused, muddled"],
["呼吸","hū xī","Verb: to breathe"],
["胡须","hú xū","Noun: beard"],
["滑冰","huá bīng","Noun: skating; Verb: to skate"],
["划船","huá chuán","Noun: rowing, rowing boat; Verb: to row a boat"],
["花生","huā shēng","Noun: peanut"],
["话题","huà tí","Noun: topic"],
["化学","huà xué","Noun: chemistry"],
["华裔","huá yì","Noun: ethnic Chinese (but non-Chinese citizen)"],
["怀念","huái niàn","Verb: to cherish the memory of, to think of"],
["缓解","huǎn jiě","Verb: to ease, to blunt, to help relieve (a crisis)"],
["幻想","huàn xiǎng","Noun: illusion, fantasy; Verb: to dream"],
["皇帝","huáng dì","Noun: emperor"],
["黄瓜","huáng guā","Noun: cucumber"],
["皇后","huáng hòu","Noun: empress"],
["黄金","huáng jīn","Noun: gold"],
["慌张","huāng zhāng","Adjective: confused, flustered"],
["挥","huī","Verb: to wave, to brandish, to wipe away"],
["灰","huī","Noun: ash, dust; Adjective: gray"],
["灰尘","huī chén","Noun: dust"],
["恢复","huī fù","Verb: to recover, to restore"],
["汇率","huì lǜ","Noun: exchange rate"],
["灰心","huī xīn","Verb: to lose heart, to be discouraged"],
["婚礼","hūn lǐ","Noun: wedding"],
["婚姻","hūn yīn","Noun: wedding, marriage"],
["伙伴","huǒ bàn","Noun: partner, companion, mate"],
["火柴","huǒ chái","Noun: match (for fire)"],
["活跃","huó yuè","Adjective: active, vigorous"],
["基本","jī běn","Adjective: basic, fundamental"],
["及格","jí gé","Verb: to pass a test"],
["激烈","jī liè","Adjective: intense, fierce"],
["系领带","jì lǐng dài","Verb: to tie one's necktie"],
["纪录","jì lù","Noun: record"],
["记录","jì lù","Noun: record"],
["纪律","jì lǜ","Noun: discipline"],
["急忙","jí máng","Adjective: hasty, in a hurry"],
["寂寞","jì mò","Adjective: lonely"],
["纪念","jì niàn","Noun: commemoration; Verb: to commemorate"],
["机器","jī qì","Noun: machine"],
["肌肉","jī ròu","Noun: muscle"],
["计算","jì suàn","Noun: calculation; Verb: to count, to calculate"],
["集体","jí tǐ","Noun: collective"],
["记忆","jì yì","Noun: memory; Verb: to remember"],
["集中","jí zhōng","Verb: to concentrate, to focus"],
["嫁","jià","Verb: to marry (woman -> men)"],
["甲","jiǎ","Number: first(ly)"],
["嘉宾","jiā bīn","Noun: honoured guest"],
["假如","jiǎ rú","Conjunction: if"],
["驾驶","jià shǐ","Verb: to drive, to pilot"],
["家庭","jiā tíng","Noun: family, household"],
["家务","jiā wù","Noun: housework"],
["家乡","jiā xiāng","Noun: hometown, native place"],
["价值","jià zhí","Noun: value, worth"],
["假装","jiǎ zhuāng","Verb: to pretend"],
["夹子","jiā zi","Noun: clip, clamp, tongs"],
["捡","jiǎn","Verb: to pick up, to gather"],
["煎","jiān","Verb: to pan fry"],
["肩膀","jiān bǎng","Noun: shoulder"],
["剪刀","jiǎn dāo","Noun: scissors"],
["艰巨","jiān jù","Adjective: arduous, formidable"],
["坚决","jiān jué","Adjective: resolute, determined"],
["艰苦","jiān kǔ","Adjective: difficult, hard"],
["建立","jiàn lì","Verb: to build, to establish"],
["简历","jiǎn lì","Noun: CV, resume"],
["键盘","jiàn pán","Noun: keyboard"],
["坚强","jiān qiáng","Adjective: strong"],
["尖锐","jiān ruì","Adjective: sharp, acute (illness)"],
["建设","jiàn shè","Noun: construction; Verb: to build, to construct"],
["健身房","jiàn shēn fáng","Noun: gym, gymnasium"],
["建议","jiàn yì","Noun: suggestion; Verb: to suggest"],
["简直","jiǎn zhí","Adverb: simply, totally"],
["建筑","jiàn zhù","Noun: building, architecture; Verb: to build, to construct"],
["讲究","jiǎng jiu","Verb: to pay attention to; Adjective: exquisite, tasteful"],
["降落","jiàng luò","Verb: to descend, to land"],
["酱油","jiàng yóu","Noun: soy sauce"],
["讲座","jiǎng zuò","Noun: lecture"],
["浇","jiāo","Verb: to water, to pour, to sprinkle"],
["教材","jiào cái","Noun: teaching material"],
["角度","jiǎo dù","Noun: angle, point of view"],
["狡猾","jiǎo huá","Adjective: sly, cunning, tricky"],
["交换","jiāo huàn","Noun: exchange; Verb: to exchange, to swap, to switch"],
["交际","jiāo jì","Noun: communication, social intercourse; Verb: socialize"],
["教练","jiào liàn","Noun: sports coach, instructor"],
["郊区","jiāo qū","Noun: suburbs"],
["胶水","jiāo shuǐ","Noun: glue"],
["教训","jiào xùn","Noun: lesson; Verb: to teach sb. a lesson"],
["节","jié","Noun: festival, holiday, segmet, joint, part; Verb: to save, to economize; Measure Word: for segments"],
["届","jiè","Verb: to become due; Measure Word: for events, meetings, etc."],
["接触","jiē chù","Verb: to touch, to contact, to get in touch with"],
["接待","jiē dài","Verb: to receive (visitor)"],
["阶段","jiē duàn","Noun: stage, section, phase"],
["解放","jiě fàng","Noun: liberation; Verb: to liberate, to emancipate"],
["结构","jié gòu","Noun: structure, makeup, composition"],
["结合","jié hé","Noun: binding; Verb: to combine, to link, to integrate"],
["接近","jiē jìn","Verb: to near, to approach, to be close to"],
["借口","jiè kǒu","Noun: excuse, pretext"],
["结论","jié lùn","Noun: conclusion"],
["节省","jié shěng","Verb: to save, to economize, to use sparingly"],
["结实","jiē shi","Adjective: solid, durable, sturdy"],
["解说员","jiě shuō yuán","Noun: commentator"],
["戒烟","jiè yān","Verb: to give up smoking"],
["结账","jié zhàng","Verb: to pay the bill"],
["接着","jiē zhe","Verb: to follow, to carry on; Adverb: then, after that"],
["戒指","jiè zhi","Noun: ring (for finger)"],
["紧","jǐn","Adjective: thight, tense, urgent"],
["进步","jìn bù","Noun: progress, improvement; Verb: to improve, make progress"],
["近代","jìn dài","Time: modern times"],
["紧急","jǐn jí","Adjective: urgent, pressing"],
["进口","jìn kǒu","Noun: import; Verb: to import"],
["尽力","jìn lì","Verb: to do all one can"],
["尽量","jǐn liàng","Adverb: to the best of one's ability"],
["谨慎","jǐn shèn","Adjective: cautious, prudent"],
["金属","jīn shǔ","Noun: metal"],
["敬爱","jìng ài","Verb: to respect and love"],
["经典","jīng diǎn","Noun: classics, scriptures; Adjective: classical"],
["精力","jīng lì","Noun: energy"],
["景色","jǐng sè","Noun: scenery, view, landscape"],
["经营","jīng yíng","Verb: to run, to operate, to engage in (business, etc.)"],
["救","jiù","Verb: to relieve, to rescue"],
["酒吧","jiǔ bā","Noun: bar, pub"],
["救护车","jiù hù chē","Noun: ambulance"],
["舅舅","jiù jiu","Noun: uncle (maternal)"],
["举","jǔ","Verb: to raise, to hold up, to elect"],
["具备","jù bèi","Verb: to possess, to have"],
["巨大","jù dà","Adjective: huge enormous"],
["聚会","jù huì","Noun: party, gathering; Verb: to party, to get together"],
["俱乐部","jù lè bù","Noun: club"],
["居然","jū rán","Adverb: unexpectedly"],
["据说","jù shuō","Adverb: it is said, reportedly"],
["具体","jù tǐ","Adjective: concrete, specific"],
["桔子","jú zi","Noun: tangerine"],
["捐","juān","Noun: tax, contribution; Verb: to contribute, to donate, to give up"],
["卷","juǎn","Noun: roll; Verb: to roll; Measure Word: for roll, spool"],
["绝对","jué duì","Adjective: absolute, unconditional"],
["决赛","jué sài","Noun: final (competition)"],
["角色","jué sè","Noun: character (in a book, play, etc.)"],
["决心","jué xīn","Noun: determination, resolution; Verb: to make up one's mind"],
["军事","jūn shì","Noun: military affairs"],
["均匀","jūn yún","Adjective: even, homogeneous"],
["卡车","kǎ chē","Noun: truck, lorry"],
["开发","kāi fā","Verb: to develop (e.g. IT), to exploit (a resource)"],
["开放","kāi fàng","Verb: to open up (for public, etc.)"],
["开幕式","kāi mù shì","Noun: opening ceremony"],
["开心","kāi xīn","Verb: to feel happy, to make fun of sb.; Adjective: happy"],
["砍","kǎn","Verb: to chop, to cut down"],
["看不起","kàn bu qǐ","Verb: to look down upon"],
["看来","kàn lái","Conjunction: it seems, it appears"],
["抗议","kàng yì","Verb: to protest"],
["烤鸭","kǎo yā","Noun: roast duck"],
["克","kè","Verb: to subdue, to restrain; Measure Word: 1 gram"],
["颗","kē","Measure Word: for grain, pearls, teeth, stars, etc."],
["课程","kè chéng","Noun: course, class"],
["克服","kè fú","Verb: to overcome, to conquer, to put up with"],
["客观","kè guān","Adjective: objective, impartial"],
["可见","kě jiàn","Conjunction: it is obvious that, it can clearly be seen that"],
["可靠","kě kào","Adjective: reliable, dependable"],
["刻苦","kè kǔ","Adjective: hardworking, assiduous"],
["可怕","kě pà","Adjective: awful, terrible"],
["客厅","kè tīng","Noun: living room"],
["恐怖","kǒng bù","Adjective: terrble, fearful, frightening"],
["空间","kōng jiān","Noun: space"],
["空闲","kòng xián","Noun: leisure; Adjective: idle"],
["控制","kòng zhì","Noun: control; Verb: to control"],
["口味","kǒu wèi","Noun: taste, flavour"],
["夸","kuā","Verb: to praise, to boast"],
["会计","kuài jì","Noun: accountant, accounting"],
["矿泉水","kuàng quán shuǐ","Noun: mineral water"],
["辣椒","là jiāo","Noun: hot pepper, chili"],
["蜡烛","là zhú","Noun: candle"],
["来自","lái zì","Verb: to come from"],
["拦","lán","Verb: to block, to hinder"],
["烂","làn","Verb: to rot; Adjective: rotten, mushy, soft"],
["狼","láng","Noun: wolf"],
["老百姓","lǎo bǎi xìng","Noun: ordinary people"],
["老板","lǎo bǎn","Noun: boss, owner"],
["劳动","láo dòng","Noun: work, labour"],
["劳驾","láo jià","Saying: excuse me"],
["姥姥","lǎo lao","Noun: grandmother (mother's mum)"],
["老实","lǎo shi","Adjective: honest, sincere"],
["老鼠","lǎo shǔ","Noun: rat, mouse"],
["乐观","lè guān","Adjective: optimistic, hopeful"],
["雷","léi","Noun: thunder"],
["类","lèi","Noun: sort, kind, category; Measure Word: for sorts, types, categories, etc."],
["梨","lí","Noun: pear"],
["粒","lì","Noun: grain; Measure Word: for small roung things"],
["礼拜天","lǐ bài tiān","Time: Sunday"],
["立方","lì fāng","Noun: cube"],
["离婚","lí hūn","Noun: divorce; Verb: to divorce (from)"],
["立即","lì jí","Adverb: immediately, at once"],
["立刻","lì kè","Adverb: immediately, at once"],
["力量","lì liàng","Noun: power, force, strength"],
["理论","lǐ lùn","Noun: theory"],
["厘米","lí mǐ","Measure Word: centimeter"],
["利润","lì rùn","Noun: profit"],
["利息","lì xī","Noun: interest (on a loan)"],
["利益","lì yì","Noun: benefit"],
["利用","lì yòng","Verb: to make use of, to utilize"],
["理由","lǐ yóu","Noun: reason, justification"],
["恋爱","liàn ài","Noun: love; Verb: to be in love, to have an affair"],
["联合","lián hé","Noun: alliance, union; Verb: to unite, to join; Adjective: combined, joint"],
["连忙","lián máng","Adverb: promptly, at once"],
["连续剧","lián xù jù","Noun: (TV) series"],
["良好","liáng hǎo","Adjective: good, favorable, fine"],
["粮食","liáng shi","Noun: food, cereals"],
["了不起","liǎo bu qǐ","Adjective: amazing, extraordnary"],
["临时","lín shí","Adjective: temporary"],
["铃","líng","Noun: bell"],
["领导","lǐng dǎo","Noun: leader, leadership; Verb: to lead"],
["灵活","líng huó","Adjective: flexible, agile, nimble"],
["零件","líng jiàn","Noun: part, component"],
["零钱","líng qián","Noun: change (money)"],
["零食","líng shí","Noun: snack"],
["领域","lǐng yù","Noun: field, domain, area, territory"],
["流传","liú chuán","Verb: to spread, to circulate, to hand down"],
["浏览","liú lǎn","Verb: to skim over, to browse, to surf (IT)"],
["龙","lóng","Noun: dragon"],
["漏","lòu","Verb: to leak"],
["露","lù","Noun: dew, syrup, nectar; Verb: to uncover, to expose, to reveal"],
["陆地","lù dì","Noun: land, dry land"],
["录取","lù qǔ","Verb: to enroll, being admitted (e.g. university)"],
["陆续","lù xù","Adverb: one after another, bit by bit"],
["录音","lù yīn","Noun: sound recording; Verb: to record"],
["轮流","lún liú","Verb: to alternate, to take turns"],
["论文","lùn wén","Noun: paper, thesis"],
["落后","luò hòu","Verb: to fall behind, to lag"],
["逻辑","luó ji","Noun: logic"],
["骂","mà","Noun: abuse; Verb: to abuse, to curse"],
["麦克风","mài kè fēng","Noun: microphone"],
["馒头","mán tou","Noun: steamed bun"],
["满足","mǎn zú","Verb: to satisfy"],
["毛","máo","Noun: hair, down; Measure Word: for 0.1 RMB"],
["毛病","máo bìng","Noun: defect, fault, trouble"],
["矛盾","máo dùn","Noun: contradiction; Adjective: contradictory"],
["冒险","mào xiǎn","Verb: to take a risk"],
["贸易","mào yì","Noun: trade"],
["魅力","mèi lì","Noun: charm, fascination"],
["眉毛","méi mao","Noun: eyebrow"],
["美术","měi shù","Noun: fine arts, art"],
["煤炭","méi tàn","Noun: coal"],
["蜜蜂","mì fēng","Noun: honeybee"],
["迷路","mí lù","Verb: to get lost, to lose the way"],
["秘密","mì mì","Noun: secret; Adjective: secret, confidential"],
["密切","mì qiè","Adjective: close, intimate"],
["秘书","mì shū","Noun: secretary"],
["谜语","mí yǔ","Noun: riddle"],
["面对","miàn duì","Verb: to face, to confront"],
["棉花","mián hua","Noun: cotton"],
["面积","miàn jī","Noun: area"],
["面临","miàn lín","Verb: to face sth., to be confronted with"],
["秒","miǎo","Time: second"],
["苗条","miáo tiao","Adjective: slim, slender, graceful"],
["描写","miáo xiě","Noun: description; Verb: to describe, to depict, to portray"],
["民主","mín zhǔ","Noun: democracy; Adjective: democratic"],
["命令","mìng lìng","Noun: order, command; Verb: to order, to command"],
["名牌","míng pái","Noun: famous brand"],
["名片","míng piàn","Noun: (business) card"],
["明确","míng què","Adjective: clear, definite, explicit"],
["名胜古迹","míng shèng gǔ jì","Noun: historical sites and scenic spots"],
["明显","míng xiǎn","Adjective: clear, obvious"],
["明信片","míng xìn piàn","Noun: postcard"],
["明星","míng xīng","Noun: star, celebrity"],
["命运","mìng yùn","Noun: fate, destiny"],
["摸","mō","Verb: to touch, to feel with the hand, to grope"],
["模仿","mó fǎng","Verb: to imitate, to copy"],
["模糊","mó hu","Adjective: fuzzy, blurred, indistinct"],
["陌生","mò shēng","Adjective: strange, unfamiliar"],
["摩托车","mó tuō chē","Noun: motorbike"],
["某","mǒu","Pronoun: some, certain"],
["目标","mù biāo","Noun: goal, target, objective"],
["目录","mù lù","Noun: catalog, table of contents"],
["目前","mù qián","Time: at present, now"],
["木头","mù tou","Noun: log of wood, blockhead"],
["哪怕","nǎ pà","Conjunction: even if"],
["难怪","nán guài","Saying: no wonder (that)"],
["难看","nán kàn","Adjective: ugly"],
["脑袋","nǎo dai","Noun: head, skull, brain"],
["内科","nèi kē","Noun: internal medicine"],
["嫩","nèn","Adjective: tender, soft, inexperienced"],
["能干","néng gàn","Adjective: able, capable, competent"],
["能源","néng yuán","Noun: energy, energy source"],
["念","niàn","Verb: to read aloud"],
["年代","nián dài","Time: decade, age, period"],
["年纪","nián jì","Noun: age"],
["宁可","nìng kě","Conjunction: would rather, preferably"],
["牛仔裤","niú zǎi kù","Noun: jeans"],
["浓","nóng","Adjective: dense, concentrated, thick"],
["农民","nóng mín","Noun: peasant, farmer"],
["农业","nóng yè","Noun: agriculture, farming"],
["女士","nǚ shì","Noun: lady, madam"],
["偶然","ǒu rán","Adverb: accidentally, by chance"],
["派","pài","Noun: school, group, pi (π); Verb: to send, to assign"],
["拍","pāi","Verb: to clap, to slap, to take (a photo)"],
["排队","pái duì","Verb: to queue, to line up"],
["排球","pái qiú","Noun: volleyball"],
["盼望","pàn wàng","Verb: to hope for, to look forward to"],
["赔偿","péi cháng","Noun: compensation; Verb: to compensate"],
["佩服","pèi fu","Verb: to admire"],
["配合","pèi hé","Verb: to coordinate, to cooperate, to fit"],
["培养","péi yǎng","Verb: to train, to cultivate, to bring up"],
["盆","pén","Noun: basin, tub, pot; Measure Word: for approx. 128 liters"],
["碰见","pèng jiàn","Verb: to run into, to bump into"],
["匹","pǐ","Noun: ordinary person; Measure Word: for horses and cloth"],
["批","pī","Verb: to criticize; Measure Word: for batches, lots, etc."],
["披","pī","Verb: to drape over one's shoulder, to crack"],
["疲劳","pí láo","Noun: wariness, fatigue; Adjective: tired, weary, exhausted"],
["皮鞋","pí xié","Noun: leather shoes"],
["批准","pī zhǔn","Verb: to approve, to ratify"],
["片","piàn","Noun: thin piece, slice, film; Measure Word: for movies, scenes, etc. pieces of things"],
["片面","piàn miàn","Adjective: unilateral, one-sided"],
["飘","piāo","Verb: to flutter, to float (in the wind)"],
["频道","pín dào","Noun: frequency, (TV) channel"],
["品种","pǐn zhǒng","Noun: variety, breed"],
["凭","píng","Noun: proof; Verb: to rely on, to lean against; Preposition: according to, on the basis of"],
["平","píng","Adjective: flat, level, calm, peaceful"],
["平常","píng cháng","Adjective: ordinary, common; Adverb: generally, usually"],
["平等","píng děng","Noun: equality; Adjective: equal"],
["平方","píng fāng","Noun: square"],
["平衡","píng héng","Noun: balance, equilibrium"],
["评价","píng jià","Verb: to assess, to evaluate"],
["平静","píng jìng","Noun: calm, quiet, tranquil"],
["平均","píng jūn","Noun: average; Adjective: average, mean"],
["破产","pò chǎn","Noun: bankruptcy; Verb: to go bankrupt"],
["破坏","pò huài","Noun: destruction, damage; Verb: to destroy, to break"],
["迫切","pò qiè","Adjective: urgent, pressing"],
["朴素","pǔ sù","Adjective: plain, simple"],
["期待","qī dài","Noun: expectation; Verb: to look forward to"],
["启发","qǐ fā","Noun: inspiration, enlightenment; Verb: to inspire, to enlighten"],
["气氛","qì fēn","Noun: atmosphere, mood"],
["奇迹","qí jì","Noun: miracle, wonder"],
["期间","qī jiān","Noun: period of time, period"],
["企图","qǐ tú","Noun: attempt; Verb: to attempt"],
["企业","qǐ yè","Noun: enterprise, company"],
["汽油","qì yóu","Noun: gas, gasoline"],
["其余","qí yú","Pronoun: the rest, the others"],
["欠","qiàn","Verb: to owe; Adjective: deficient"],
["浅","qiǎn","Adjective: shallow, light"],
["牵","qiān","Verb: to pull, to lead, to hold hands"],
["前途","qián tú","Noun: prospect, future"],
["谦虚","qiān xū","Adjective: modest"],
["签字","qiān zì","Verb: to sign (signature)"],
["抢","qiǎng","Verb: to grab, to rob"],
["枪","qiāng","Noun: gun, spear"],
["强调","qiáng diào","Verb: to emphasize, to stress, to underling"],
["强烈","qiáng liè","Adjective: intense, strong, violent"],
["瞧","qiáo","Verb: to look at, to see"],
["巧妙","qiǎo miào","Adjective: ingenious, clever"],
["悄悄","qiāo qiāo","Adverb: quietly, secretly"],
["切","qiē","Verb: to cut, to chop"],
["亲爱","qīn ài","Adjective: dear, beloved"],
["勤奋","qín fèn","Adjective: hardworking, diligent"],
["勤劳","qín láo","Adjective: hardworking, industrious"],
["侵略","qīn lüè","Noun: invasion, aggression; Verb: to invade"],
["亲切","qīn qiè","Noun: friendliness, hospitality; Adjective: kind, cordial, amiable"],
["亲自","qīn zì","Adverb: personally"],
["青","qīng","Adjective: blue/green"],
["青春","qīng chūn","Time: youth, youthfulness"],
["清淡","qīng dàn","Adjective: light (food)"],
["情景","qíng jǐng","Noun: scene, sight, condition, circumstances"],
["请求","qǐng qiú","Noun: request; Verb: to request, to ask"],
["青少年","qīng shào nián","Noun: young person, teenager"],
["轻视","qīng shì","Verb: to look down upon, to contempt"],
["情绪","qíng xù","Noun: feeling, mood, sentiment"],
["庆祝","qìng zhù","Verb: to celebrate"],
["球迷","qiú mí","Noun: football fan"],
["娶","qǔ","Verb: to marry (men -> woman)"],
["去世","qù shì","Verb: to pass away, to die"],
["趋势","qū shì","Noun: trend, tendency"],
["取消","qǔ xiāo","Noun: cancellation; Verb: to cancel"],
["劝","quàn","Verb: to advise, to persuade, to encourage"],
["圈","quān","Noun: circle, ring, loop; Measure Word: for loops, laps, etc."],
["权利","quán lì","Noun: right, privilege"],
["权力","quán lì","Noun: power, authority"],
["全面","quán miàn","Adjective: all-around, overall, comprehensive"],
["确定","què dìng","Verb: to make sure, to define, to determine"],
["缺乏","quē fá","Noun: shortage; Verb: to be short of, to lack"],
["确认","què rèn","Noun: confirmation; Verb: to confirm, to verify"],
["燃烧","rán shāo","Verb: to burn, to kindle"],
["嚷","rǎng","Verb: to blurt out, to shout"],
["绕","rào","Verb: to wind, to coil (around), to go around"],
["热爱","rè ài","Verb: to love ardently, to adore"],
["热烈","rè liè","Adjective: warm (welcome, etc.), enthusiastic"],
["热心","rè xīn","Noun: enthusiasm; Adjective: enthusiastic, ardent, warmhearted"],
["忍不住","rěn bu zhù","Verb: cannot help, unable to bear"],
["人才","rén cái","Noun: talent, talented person"],
["人口","rén kǒu","Noun: population"],
["人类","rén lèi","Noun: humanity, mankind"],
["人生","rén shēng","Noun: life, human life"],
["人事","rén shì","Noun: human affairs, personnel"],
["人物","rén wù","Noun: character, protagonist"],
["人员","rén yuán","Noun: staff, personnel"],
["日常","rì cháng","Adjective: daily"],
["日程","rì chéng","Noun: schedule"],
["日历","rì lì","Noun: calendar"],
["日期","rì qī","Noun: date"],
["日用品","rì yòng pǐn","Noun: articles for daily use"],
["融化","róng huà","Verb: to melt, to thaw"],
["荣幸","róng xìng","Adjective: honoured"],
["荣誉","róng yù","Noun: honour, glory"],
["如何","rú hé","Adverb: how, in what way"],
["如今","rú jīn","Time: nowadays"],
["软件","ruǎn jiàn","Noun: software"],
["弱","ruò","Adjective: weak"],
["洒","sǎ","Verb: to sprinkle, to spray"],
["嗓子","sǎng zi","Noun: throat, voice"],
["傻","shǎ","Adjective: foolish"],
["杀","shā","Verb: to kill"],
["沙漠","shā mò","Noun: desert"],
["沙滩","shā tān","Noun: beach"],
["晒","shài","Verb: to share files, to dry in the sun, to sunbathe"],
["删除","shān chú","Verb: to delete"],
["闪电","shǎn diàn","Noun: lightning"],
["善良","shàn liáng","Adjective: kindhearted, good, honest"],
["善于","shàn yú","Verb: to be good at"],
["扇子","shàn zi","Noun: fan"],
["上当","shàng dàng","Verb: to be fooled"],
["商品","shāng pǐn","Noun: good, commodity"],
["商业","shāng yè","Noun: business, commerce, trade"],
["勺子","sháo zi","Noun: spoon"],
["蛇","shé","Noun: snake"],
["设备","shè bèi","Noun: equipment, facilities"],
["舍不得","shě bu de","Verb: reluctant to give up or let go"],
["设计","shè jì","Noun: design, plan; Verb: to design, to plan"],
["射击","shè jī","Verb: to shoot, to fire (a gun)"],
["设施","shè shī","Noun: facility, installation"],
["舌头","shé tou","Noun: tongue"],
["摄影","shè yǐng","Verb: to take a photo, to shoot a movie"],
["伸","shēn","Verb: to stretch, to extend"],
["身材","shēn cái","Noun: figure, stature"],
["身份","shēn fèn","Noun: identity, status"],
["神话","shén huà","Noun: fairy tale, myth"],
["神经","shén jīng","Noun: nerve"],
["深刻","shēn kè","Adjective: profound, deep"],
["神秘","shén mì","Noun: mystery; Adjective: mysterious"],
["升","shēng","Verb: to promote, to raise; Measure Word: 1 liter"],
["生产","shēng chǎn","Noun: production; Verb: to produce, to manufacture"],
["声调","shēng diào","Noun: tone, note"],
["生动","shēng dòng","Adjective: vivid, lively"],
["胜利","shèng lì","Noun: victory, triumph"],
["省略","shěng lüè","Verb: to leave out, to omit"],
["绳子","shéng zi","Noun: string, rope, cord"],
["诗","shī","Noun: poem"],
["士兵","shì bīng","Noun: soldier"],
["时代","shí dài","Time: time, era, epoch"],
["似的","shì de","Conjunction: (seems) as if"],
["是否","shì fǒu","Conjunction: whether (or not)"],
["实话","shí huà","Noun: truth"],
["实践","shí jiàn","Verb: to practice, to carry out"],
["使劲儿","shǐ jìn r","Verb: to exert all one's strength"],
["试卷","shì juàn","Noun: examination paper"],
["时刻","shí kè","Time: moment"],
["时髦","shí máo","Adjective: fashionable"],
["失眠","shī mián","Noun: insomnia; Verb: be unable to sleep"],
["时期","shí qī","Noun: period, phase"],
["失去","shī qù","Verb: to lose (sth.)"],
["时尚","shí shàng","Noun: fashion"],
["事实","shì shí","Noun: fact"],
["石头","shí tou","Noun: stone"],
["食物","shí wù","Noun: food"],
["事物","shì wù","Noun: thing, object"],
["实习","shí xí","Noun: practice, internship; Verb: to practice"],
["实现","shí xiàn","Verb: to realize, to achieve, to bring about"],
["事先","shì xiān","Adverb: in advance, beforehand"],
["实行","shí xíng","Verb: to put into practice, to carry out"],
["实验","shí yàn","Noun: experiment; Verb: to experiment"],
["失业","shī yè","Noun: unemployment; Verb: to lose one's job; Adjective: unemployed"],
["实用","shí yòng","Adjective: practical, pragmatisch, applied"],
["始终","shǐ zhōng","Adverb: from beginning to end"],
["手工","shǒu gōng","Noun: hondwork; Adjective: manual"],
["收获","shōu huò","Noun: result, gain, harvest; Verb: to harvest"],
["收据","shōu jù","Noun: receipt"],
["寿命","shòu mìng","Noun: life span, life expectancy"],
["受伤","shòu shāng","Verb: to get injured"],
["手术","shǒu shù","Noun: operation, surgery"],
["手套","shǒu tào","Noun: gloves"],
["手续","shǒu xù","Noun: procedure, formality"],
["手指","shǒu zhǐ","Noun: finger"],
["鼠标","shǔ biāo","Noun: mouse (IT)"],
["蔬菜","shū cài","Noun: vegetables"],
["书架","shū jià","Noun: bookshelf"],
["数据","shù jù","Noun: data"],
["熟练","shú liàn","Adjective: skilled, practiced, proficient"],
["数码","shù mǎ","Noun: number, figure; Adjective: digital"],
["输入","shū rù","Verb: to import, to input"],
["舒适","shū shì","Adjective: comfortable, cozy"],
["属于","shǔ yú","Verb: to belong to, to be part of"],
["梳子","shū zi","Noun: comb"],
["甩","shuǎi","Verb: to throw, to swing, to move back and forth"],
["摔","shuāi","Verb: to fall, to throw down"],
["双方","shuāng fāng","Noun: both sides; Adjective: bilateral"],
["税","shuì","Noun: tax, duty"],
["说不定","shuō bu dìng","Adverb: maybe, cannot say for sure"],
["说服","shuō fú","Verb: to persuade, to convince"],
["撕","sī","Verb: to tear up"],
["丝绸","sī chóu","Noun: silk, silk cloth"],
["丝毫","sī háo","Adjective: the slightes amount or degree, very little"],
["似乎","sì hū","Adverb: apparently, it seems as if, seemingly"],
["思考","sī kǎo","Verb: to ponder over, to think over, to reflect upon"],
["寺庙","sì miào","Noun: temple, monastery"],
["私人","sī rén","Noun: private (person); Adjective: private"],
["思想","sī xiǎng","Noun: idea, thought, thinking"],
["宿舍","sù shè","Noun: dormitory"],
["碎","suì","Verb: to break into pieces; Adjective: broken (into pieces)"],
["随时","suí shí","Adverb: at all time, at any time"],
["损失","sǔn shī","Noun: loss, damage; Verb: to lose, to damage"],
["所","suǒ","Adverb: actually; Measure Word: for houses, buildings, institutions"],
["锁","suǒ","Noun: lock; Verb: to lock up"],
["缩短","suō duǎn","Verb: to curtail, to cut down"],
["所谓","suǒ wèi","Adverb: so-called"],
["缩小","suō xiǎo","Verb: to reduce, to shrink, to lessen"],
["塔","tǎ","Noun: tower"],
["太极拳","tài jí quán","Noun: shadowboxing, Taiji"],
["台阶","tái jiē","Noun: stairs, step"],
["太太","tài tai","Noun: wife, Madame, Mrs."],
["谈判","tán pàn","Noun: negotiation, talks; Verb: to negotiate"],
["坦率","tǎn shuài","Adjective: frank, open, candid"],
["烫","tàng","Verb: to burn, to iron; Adjective: hot (food, etc.)"],
["桃","táo","Noun: peach"],
["逃","táo","Verb: to escape, to run away, to flee"],
["套","tào","Noun: cover; Verb: to cover with; Measure Word: for sets of things"],
["逃避","táo bì","Verb: to escape, to avoid, to shirk"],
["特殊","tè shū","Adjective: special, unusual"],
["特意","tè yì","Adverb: specially, expressly"],
["特征","tè zhēng","Noun: distinctive feature, characteristic"],
["疼爱","téng ài","Verb: to love dearly"],
["提","tí","Verb: to carry, to raise"],
["提倡","tí chàng","Verb: to promote, to advocate"],
["提纲","tí gāng","Noun: key points, outline"],
["体会","tǐ huì","Verb: to know (through experience), to experience"],
["体积","tǐ jī","Noun: volume"],
["题目","tí mù","Noun: topic, title"],
["体贴","tǐ tiē","Adjective: considerate"],
["提问","tí wèn","Verb: to raise a question"],
["体现","tǐ xiàn","Verb: to embody, to incarnate"],
["体验","tǐ yàn","Verb: to experience (for oneself)"],
["天空","tiān kōng","Noun: sky"],
["田野","tián yě","Noun: field, open land"],
["天真","tiān zhēn","Adjective: naive, innocent"],
["调皮","tiáo pí","Adjective: naughty, tricky"],
["挑战","tiǎo zhàn","Noun: challange"],
["调整","tiáo zhěng","Noun: adjustment; Verb: to adjust, to revise"],
["铜","tóng","Noun: copper"],
["通常","tōng cháng","Adverb: regular, usually, normally"],
["痛苦","tòng kǔ","Noun: pain, suffering; Adjective: painful"],
["痛快","tòng kuài","Adjective: delighted, very happy"],
["同时","tóng shí","Time: at the same time, simultaneously"],
["通讯","tōng xùn","Noun: communication, news report"],
["统一","tǒng yī","Verb: to unify, to unite, to integrate"],
["统治","tǒng zhì","Noun: regime, government; Verb: to rule, to govern"],
["透明","tòu míng","Adjective: transparent"],
["投资","tóu zī","Noun: investment; Verb: to invest"],
["吐","tù","Verb: to vomit"],
["突出","tū chū","Adjective: outstanding"],
["土地","tǔ dì","Noun: land, soil, territory"],
["土豆","tǔ dòu","Noun: potato"],
["兔子","tù zi","Noun: rabbit"],
["团","tuán","Noun: group, regiment; Measure Word: for ball-like things"],
["退","tuì","Verb: to return, to decline, to withdraw"],
["退步","tuì bù","Noun: regression; Verb: to regress, to fall behind, to go backward"],
["推辞","tuī cí","Verb: to decline, to turn down"],
["推广","tuī guǎng","Verb: to spread, to popularize"],
["推荐","tuī jiàn","Noun: recommendation; Verb: to recommend"],
["退休","tuì xiū","Noun: retirement; Verb: to retire"],
["歪","wāi","Adjective: crooked, devious"],
["外交","wài jiāo","Noun: diplomacy, foreign affairs"],
["弯","wān","Noun: a curve; Verb: to bend, to curve; Adjective: bent, curved"],
["玩具","wán jù","Noun: toy"],
["完美","wán měi","Adjective: perfect"],
["完善","wán shàn","Verb: to improve, to make perfect; Adjective: perfect"],
["万一","wàn yī","Noun: contingency; Conjunction: in case"],
["完整","wán zhěng","Adjective: complete, intact"],
["往返","wǎng fǎn","Adverb: back and forth, to and from"],
["王子","wáng zǐ","Noun: prince"],
["胃","wèi","Noun: stomach"],
["尾巴","wěi ba","Noun: tail"],
["未必","wèi bì","Adverb: not necessarily"],
["伟大","wěi dà","Adjective: great, mighty"],
["违反","wéi fǎn","Verb: to violate (law)"],
["危害","wēi hài","Noun: endangerment; Verb: to endanger, to harm"],
["维护","wéi hù","Verb: to defend, to safeguard, to maintain"],
["围巾","wéi jīn","Noun: scarf"],
["未来","wèi lái","Noun: future"],
["委屈","wěi qu","Verb: to feel wronged"],
["围绕","wéi rào","Verb: to revolve around, to surround"],
["卫生间","wèi shēng jiān","Noun: bathroom, WC"],
["委托","wěi tuō","Verb: to entrust, to commission, to consign"],
["微笑","wēi xiào","Noun: smile; Verb: to smile"],
["威胁","wēi xié","Noun: threat, menace; Verb: to threaten, to menace"],
["唯一","wéi yī","Adverb: only, sole"],
["位置","wèi zhì","Noun: position, place"],
["闻","wén","Verb: to hear, to smell"],
["吻","wěn","Noun: kiss; Verb: to kiss"],
["稳定","wěn dìng","Noun: stability; Verb: to stabalize; Adjective: steady, stable"],
["问候","wèn hòu","Verb: to send a greeting"],
["文件","wén jiàn","Noun: document, file"],
["文具","wén jù","Noun: stationery, writing materials"],
["文明","wén míng","Noun: civilization, culture; Adjective: civilized"],
["温暖","wēn nuǎn","Adjective: warm"],
["温柔","wēn róu","Adjective: gentle, soft, tender"],
["文学","wén xué","Noun: literature"],
["卧室","wò shì","Noun: bedroom"],
["雾","wù","Noun: fog"],
["物理","wù lǐ","Noun: physics"],
["无奈","wú nài","Verb: to have no choice"],
["武器","wǔ qì","Noun: weapon, arms"],
["无数","wú shù","Adjective: countless, innumerable"],
["武术","wǔ shù","Noun: martial arts"],
["物质","wù zhì","Noun: matter, substance, material"],
["屋子","wū zi","Noun: room, house"],
["系","xì","Noun: system, department"],
["细节","xì jié","Noun: detail, particulars"],
["戏剧","xì jù","Noun: drama, play, theater"],
["吸收","xī shōu","Verb: to absorb, to soak up, to assimilate"],
["系统","xì tǒng","Noun: system"],
["吓","xià","Verb: to frighten, to scare"],
["瞎","xiā","Adjective: blind; Adverb: groundlessly, foolishly, aimlessly"],
["下载","xià zài","Verb: to download"],
["县","xiàn","Noun: county"],
["显得","xiǎn de","Verb: to seem, to look, to appear"],
["现金","xiàn jīn","Noun: cash"],
["显然","xiǎn rán","Adjective: clear, evident"],
["现实","xiàn shí","Noun: reality, actuality; Adjective: real, actual"],
["显示","xiǎn shì","Noun: Display; Verb: to show, to display, to demonstrate"],
["现象","xiàn xiàng","Noun: appearance, phenomenon"],
["鲜艳","xiān yàn","Adjective: bright-coloured, colourful"],
["项","xiàng","Noun: neck, point, item; Measure Word: for tasks, events, etc."],
["相处","xiāng chǔ","Verb: to get along with each other"],
["相当","xiāng dāng","Verb: be quivalent to; Adjective: apropriate; Adverb: quite, rather, fairly"],
["相对","xiāng duì","Verb: to face each other; Adverb: relatively, comperatively"],
["相关","xiāng guān","Noun: correlation, dependence; Verb: to be interrelated"],
["项链","xiàng liàn","Noun: necklace"],
["项目","xiàng mù","Noun: item, project, sports event"],
["想念","xiǎng niàn","Verb: to miss, to remember with longing"],
["橡皮","xiàng pí","Noun: rubber, eraser"],
["象棋","xiàng qí","Noun: Chinese chess"],
["享受","xiǎng shòu","Noun: enjoyment, pleasure; Verb: to enjoy"],
["相似","xiāng sì","Verb: to resemble, to be similar to"],
["想象","xiǎng xiàng","Noun: imagination; Verb: to imagine, to visualize"],
["象征","xiàng zhēng","Noun: symbol; Verb: to symbolize, to stand for"],
["小吃","xiǎo chī","Noun: snack, refreshments"],
["消费","xiāo fèi","Noun: consumption; Verb: to consume"],
["消化","xiāo huà","Noun: digestion; Verb: to digest"],
["小伙子","xiǎo huǒ zi","Noun: young fellow"],
["效率","xiào lǜ","Noun: efficiency"],
["小麦","xiǎo mài","Noun: wheat"],
["消灭","xiāo miè","Noun: annihilation; Verb: to eliminate, to perish"],
["小气","xiǎo qi","Adjective: stingy, petty, miserly"],
["消失","xiāo shī","Verb: to disappear, to fade away"],
["销售","xiāo shòu","Noun: sales; Verb: to sell"],
["孝顺","xiào shun","Verb: to be obedient to one's parents"],
["小偷","xiǎo tōu","Noun: thief"],
["斜","xié","Adjective: inclined, slanting, oblique"],
["歇","xiē","Verb: to rest"],
["协调","xié tiáo","Verb: to coordinate, to harmonize"],
["信封","xìn fēng","Noun: envelope"],
["信号","xìn hào","Noun: signal"],
["心理","xīn lǐ","Noun: psychology, mentality; Adjective: psychological, menatl"],
["欣赏","xīn shǎng","Verb: to enjoy, to appreciate"],
["信息","xìn xī","Noun: information, news"],
["心脏","xīn zàng","Noun: heart"],
["形成","xíng chéng","Verb: to form, to take shape"],
["行动","xíng dòng","Noun: action, operation; Verb: to move, to act"],
["幸亏","xìng kuī","Adverb: furtunately, luckily"],
["行人","xíng rén","Noun: pedestrian"],
["形容","xíng róng","Noun: description; Verb: to describe"],
["形势","xíng shì","Noun: situation, circumstances, terrain"],
["形式","xíng shì","Noun: form, shape"],
["行为","xíng wéi","Noun: action, conduct, behaviour, activity"],
["形象","xíng xiàng","Noun: image, appearance, figure"],
["幸运","xìng yùn","Noun: luck, fortune; Adjective: lucky, fortunate"],
["性质","xìng zhì","Noun: nature, character"],
["形状","xíng zhuàng","Noun: form, shape"],
["胸","xiōng","Noun: chest"],
["兄弟","xiōng dì","Noun: brothers"],
["雄伟","xióng wěi","Adjective: grand, magnificent"],
["修改","xiū gǎi","Noun: modification; Verb: to modify, to amend, to revise"],
["休闲","xiū xián","Noun: leisure"],
["叙述","xù shù","Noun: narration; Verb: to tell, to relate"],
["虚心","xū xīn","Adjective: modest"],
["宣布","xuān bù","Verb: to declare, to announce"],
["宣传","xuān chuán","Noun: propaganda; Verb: to propagte, to disseminate"],
["选举","xuǎn jǔ","Noun: election; Verb: to elect"],
["学期","xué qī","Noun: term, semester"],
["学术","xué shù","Noun: learning, science"],
["学问","xué wen","Noun: knowledge"],
["训练","xùn liàn","Noun: training; Verb: to train, to drill"],
["迅速","xùn sù","Adjective: rapid, speedy, quick"],
["询问","xún wèn","Verb: to inquire"],
["寻找","xún zhǎo","Verb: to seek, to look for"],
["延长","yán cháng","Verb: to prolong, to extend"],
["宴会","yàn huì","Noun: banquet, feast"],
["严肃","yán sù","Adjective: solemn, serious"],
["痒","yǎng","Verb: to itch, to tickle"],
["样式","yàng shì","Noun: type, style, pattern"],
["阳台","yáng tái","Noun: balcony"],
["摇","yáo","Verb: to shake, to sway"],
["咬","yǎo","Verb: to bite"],
["腰","yāo","Noun: waist, lower back"],
["要不","yào bù","Conjunction: otherwise"],
["要是","yào shi","Conjunction: if, in case"],
["夜","yè","Noun: night"],
["液体","yè tǐ","Noun: liquid"],
["业务","yè wù","Noun: business, professional work"],
["业余","yè yú","Noun: spare time; Adjective: amateur"],
["乙","yǐ","Number: second(ly)"],
["一辈子","yí bèi zi","Noun: a lifetime"],
["一旦","yí dàn","Time: in one day; Conjunction: in case, if, once"],
["移动","yí dòng","Noun: movement; Verb: to move, to shift; Adjective: mobile, portable"],
["遗憾","yí hàn","Verb: to regret; Adjective: regrettable"],
["以及","yǐ jí","Conjunction: as well as"],
["以来","yǐ lái","Adverb: since"],
["一路平安","yí lù píng ān","Saying: have a save trip!"],
["议论","yì lùn","Noun: discussion; Verb: to discuss, to comment on"],
["移民","yí mín","Noun: immigrant; Verb: to immigrate, to migrate"],
["依然","yī rán","Adverb: still, as before"],
["意外","yì wài","Noun: accident; Adjective: unexpected, accidental"],
["疑问","yí wèn","Noun: question, doubt"],
["义务","yì wù","Noun: duty, obligation; Adjective: voluntary"],
["意义","yì yì","Noun: meaning, sense, significance"],
["一致","yí zhì","Noun: agreement; Adjective: identical, unanimous (views, etc.)"],
["银","yín","Noun: silver; Adjective: silver (colour)"],
["因而","yīn ér","Conjunction: thus, as a result"],
["因素","yīn sù","Noun: element, factor"],
["硬币","yìng bì","Noun: coin"],
["应付","yìng fu","Verb: to deal with, to cope with"],
["硬件","yìng jiàn","Noun: hardware"],
["迎接","yíng jiē","Verb: to greet, to welcome, to meet"],
["英俊","yīng jùn","Adjective: handsome and smart"],
["应聘","yìng pìn","Verb: to apply for a job"],
["英雄","yīng xióng","Noun: hero"],
["营养","yíng yǎng","Noun: nutrition, nourishment"],
["营业","yíng yè","Verb: to do business, to trade"],
["应用","yìng yòng","Noun: application; Verb: to apply, to use"],
["影子","yǐng zi","Noun: shadow"],
["拥抱","yōng bào","Verb: to embrace, to hug"],
["拥挤","yōng jǐ","Verb: to squeeze, to press; Adjective: crowded"],
["勇气","yǒng qì","Noun: courage"],
["用途","yòng tú","Noun: application, use, purpos"],
["幼儿园","yòu ér yuán","Noun: kintergarten, nursery school"],
["优惠","yōu huì","Adjective: preferential, favourable"],
["悠久","yōu jiǔ","Adjective: long, longstanding"],
["邮局","yóu jú","Noun: post office"],
["游览","yóu lǎn","Verb: to visit, to go sightseeing"],
["有利","yǒu lì","Adjective: advantageous, beneficial"],
["优美","yōu měi","Adjective: fine, graceful"],
["优势","yōu shì","Noun: superiority, dominance, advantage"],
["犹豫","yóu yù","Verb: to hesitate"],
["油炸","yóu zhá","Verb: to deep fry"],
["预报","yù bào","Noun: forecast"],
["预订","yù dìng","Noun: booking; Verb: to book, to subscribe for"],
["预防","yù fáng","Noun: prevention, prophylaxis; Verb: to prevent"],
["娱乐","yú lè","Noun: amusement, entertainment; Verb: to amuse, to entertain"],
["玉米","yù mǐ","Noun: corn, maize"],
["与其","yǔ qí","Conjunction: rather than"],
["语气","yǔ qì","Noun: tone, manner of speaking"],
["宇宙","yǔ zhòu","Noun: universe, cosmos"],
["元旦","Yuán dàn","Noun: New Year's Day"],
["缘故","yuán gù","Noun: reason, cause"],
["原料","yuán liào","Noun: raw material"],
["愿望","yuàn wàng","Noun: desire, wish"],
["原则","yuán zé","Noun: principle"],
["晕","yūn","Verb: to pass out, to faint; Adjective: dizzy, faint, confused"],
["运气","yùn qi","Noun: luck, fate"],
["运输","yùn shū","Noun: transport; Verb: to transport"],
["运用","yùn yòng","Verb: to use, to utilize"],
["灾害","zāi hài","Noun: calamity, disaster"],
["再三","zài sān","Adverb: again and again"],
["赞成","zàn chéng","Verb: to approve of, to agree with"],
["赞美","zàn měi","Noun: applause, praise; Verb: to praise, to admire"],
["造成","zào chéng","Verb: to bring about, to create, to cause"],
["糟糕","zāo gāo","Adjective: terrible, bad"],
["则","zé","Noun: norm, standard; Verb: to follow (rule, etc.); Conjunction: then; Measure Word: for written items"],
["责备","zé bèi","Verb: to blame, to criticize"],
["摘","zhāi","Verb: to pick, to pluck, to take off (glasses, etc.)"],
["展开","zhǎn kāi","Verb: to unfold, to carry out, to spread out"],
["展览","zhǎn lǎn","Noun: exhibition; Verb: to exhibit"],
["粘贴","zhān tiē","Verb: to stick, to affix, to paste"],
["占线","zhàn xiàn","Adjective: busy (phone)"],
["战争","zhàn zhēng","Noun: war"],
["涨","zhǎng","Verb: to rise, to go up"],
["账户","zhàng hù","Noun: bank account"],
["掌握","zhǎng wò","Verb: to grasp, to master, to control"],
["照常","zhào cháng","Adverb: as usual"],
["招待","zhāo dài","Noun: reception; Verb: to entertain (guests), to serve, to receive"],
["召开","zhào kāi","Verb: to convene, to convoke, to call together"],
["着凉","zháo liáng","Verb: to catch a cold"],
["哲学","zhé xué","Noun: philosophy"],
["阵","zhèn","Noun: disposition of troops; Conjunction: for short periods or events"],
["振动","zhèn dòng","Noun: vibration; Verb: to vibrate"],
["诊断","zhěn duàn","Noun: diagnosis; Verb: to diagnose"],
["针对","zhēn duì","Verb: to be aimed at, to be directed against"],
["真理","zhēn lǐ","Noun: truth"],
["真实","zhēn shí","Adjective: real, true"],
["枕头","zhěn tou","Noun: pillow"],
["珍惜","zhēn xī","Verb: to value, to cherish"],
["正","zhèng","Adjective: upright, honest; Adverb: just, upright"],
["睁","zhēng","Verb: to open (the eyes)"],
["政策","zhèng cè","Noun: policy"],
["政府","zhèng fǔ","Noun: government"],
["整个","zhěng gè","Adjective: whole, entire"],
["证件","zhèng jiàn","Noun: certificate"],
["证据","zhèng jù","Noun: evidence, proof"],
["争论","zhēng lùn","Noun: argument, debate; Verb: to argue, to debate"],
["挣钱","zhèng qián","Verb: to make money"],
["征求","zhēng qiú","Verb: to solicit, to seek, to ask for"],
["争取","zhēng qǔ","Verb: to strive for, to fight for"],
["整体","zhěng tǐ","Noun: whole entity"],
["政治","zhèng zhì","Noun: politics"],
["直","zhí","Verb: to straighten; Adjective: straight, direct"],
["支","zhī","Noun: branch, division; Verb: to support; Measure Word: for stick-like objects"],
["指导","zhǐ dǎo","Noun: guidance; Verb: to guide, to direct"],
["制定","zhì dìng","Verb: to formulate, to work out, to draw up"],
["制度","zhì dù","Noun: system"],
["智慧","zhì huì","Noun: wisdom, intelligence, knowledge"],
["指挥","zhǐ huī","Noun: conductor; Verb: to conduct, to command, to direct"],
["至今","zhì jīn","Time: until now, until today"],
["治疗","zhì liáo","Noun: medical treatment; Verb: to treat, to cure"],
["支票","zhī piào","Noun: check (bank)"],
["执行","zhí xíng","Verb: to carry out, to execute"],
["秩序","zhì xù","Noun: order, orderly state"],
["至于","zhì yú","Conjunction: to go so far as to, with regard to"],
["志愿者","zhì yuàn zhě","Noun: volunteer"],
["执照","zhí zhào","Noun: license"],
["制作","zhì zuò","Verb: to make, to manufacture, to produce"],
["重","zhòng","Adjective: heavy, serious; Adverb: heavily"],
["钟","zhōng","Noun: clock, bell; Measure Word: o'clock"],
["中介","zhōng jiè","Noun: agency, agent"],
["重量","zhòng liàng","Noun: weight"],
["中心","zhōng xīn","Noun: center"],
["中旬","zhōng xún","Time: middle third of a month"],
["周到","zhōu dao","Adjective: thoughtful, considerate"],
["煮","zhǔ","Verb: to cook, to boil"],
["逐步","zhú bù","Adverb: step by step"],
["注册","zhù cè","Verb: to register"],
["主持","zhǔ chí","Verb: to direct, to manage, to preside over"],
["祝福","zhù fú","Verb: to bless, to wish well"],
["嘱咐","zhǔ fù","Verb: to exhort, to enjoin, to tell"],
["主观","zhǔ guān","Adjective: subjectiv"],
["主人","zhǔ rén","Noun: host, master"],
["主席","zhǔ xí","Noun: chairman"],
["主张","zhǔ zhāng","Noun: viewpoint, stand; Verb: to advocate, to stand for"],
["竹子","zhú zi","Noun: bamboo"],
["抓紧","zhuā jǐn","Verb: to grasp firmly, to pay special attention to, to seize"],
["转变","zhuǎn biàn","Noun: change; Verb: to change, to transform"],
["转告","zhuǎn gào","Verb: to pass on (a message, etc.), to transmit"],
["专家","zhuān jiā","Noun: expert, specialist"],
["专心","zhuān xīn","Noun: concentration; Verb: to concentrate; Adjective: concentrated, attentive"],
["装","zhuāng","Noun: dress, clothing, costume; Verb: to pretend, to install, to fix, to load, to pack"],
["状况","zhuàng kuàng","Noun: condition, state, situation"],
["装饰","zhuāng shì","Noun: decoration; Verb: to decorate"],
["状态","zhuàng tài","Noun: state, condition"],
["追求","zhuī qiú","Verb: to pursue, to seek after"],
["紫","zǐ","Adjective: purple"],
["自从","zì cóng","Adverb: ever since; Preposition: since"],
["自动","zì dòng","Adjective: automatic"],
["资格","zī gé","Noun: qualifications"],
["自豪","zì háo","Adjective: proud"],
["资金","zī jīn","Noun: funds, capital"],
["自觉","zì jué","Adjective: aware, conscious, on one's own initiative"],
["资料","zī liào","Noun: material, data, resources, profile (IT)"],
["字幕","zì mù","Noun: caption, subtitle"],
["姿势","zī shì","Noun: gesture, posture, pose"],
["自私","zì sī","Adjective: selfish"],
["自信","zì xìn","Noun: (self-)confidence; Adjective: (self-)confident"],
["咨询","zī xún","Noun: consultation; Verb: to consult, to seek advice"],
["自由","zì yóu","Noun: freedom, liberty; Adjective: free"],
["自愿","zì yuàn","Adjective: voluntary"],
["资源","zī yuán","Noun: resources"],
["总裁","zǒng cái","Noun: general director"],
["总共","zǒng gòng","Adverb: altogether, in total"],
["综合","zōng hé","Noun: Synthese; Verb: to integrate, to sum up; Adjective: synthesized, integrated"],
["宗教","zōng jiào","Noun: religion"],
["总理","zǒng lǐ","Noun: premier, prime minister"],
["总算","zǒng suàn","Adverb: finally, in the end, at long last"],
["总统","zǒng tǒng","Noun: president (of a country)"],
["总之","zǒng zhī","Conjunction: in short, in a word"],
["祖国","zǔ guó","Noun: fatherland, homeland"],
["组合","zǔ hé","Noun: association, combination; Verb: to make up, to compose, to constitute"],
["祖先","zǔ xiān","Noun: ancestor"],
["阻止","zǔ zhǐ","Verb: to prevent, to stop"],
["醉","zuì","Adjective: intoxicated, drunk"],
["最初","zuì chū","Time: first, initial"],
["罪犯","zuì fàn","Noun: criminal"],
["尊敬","zūn jìng","Noun: respect, esteem; Verb: to respect, to revere"],
["遵守","zūn shǒu","Verb: to abide by, to comply with"],
["作品","zuò pǐn","Noun: works (literature, art)"],
["作为","zuò wéi","Noun: conduct, ac; Verb: to accomplish, to act as, to take for; Conjunction: as"],
["作文","zuò wén","Noun: composition; Verb: to write an essay"]
]};

